/* Generated by Nim Compiler v1.9.1 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg;
typedef struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A;
typedef struct tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ;
typedef struct tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct RootObj RootObj;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
typedef struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ;
typedef struct tyTuple__0F3Kz25HWtRatQmCDVHWEA tyTuple__0F3Kz25HWtRatQmCDVHWEA;
typedef struct tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw;
typedef struct tyTuple__0hEbbYmlam6yzyW5MFo9cjg tyTuple__0hEbbYmlam6yzyW5MFo9cjg;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ tySequence__xv3aaFd3JCw8NbmALHiezQ;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content tySequence__xv3aaFd3JCw8NbmALHiezQ_Content;
typedef struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA tyTuple__sPaDkVPSC0MkcoXCxPH9ccA;
typedef struct tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyTuple__XOVT24GHXwqiEj5GCsEGCA tyTuple__XOVT24GHXwqiEj5GCsEGCA;
typedef struct tySequence__PrBYolTs4TOSgE8v5oqDUQ tySequence__PrBYolTs4TOSgE8v5oqDUQ;
typedef struct tySequence__PrBYolTs4TOSgE8v5oqDUQ_Content tySequence__PrBYolTs4TOSgE8v5oqDUQ_Content;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NU8 tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA;
struct tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A {
NI bytes;
NI16* data;
};
struct tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ {
NI32 cb;
NCSTRING lpReserved;
NCSTRING lpDesktop;
NCSTRING lpTitle;
NI32 dwX;
NI32 dwY;
NI32 dwXSize;
NI32 dwYSize;
NI32 dwXCountChars;
NI32 dwYCountChars;
NI32 dwFillAttribute;
NI32 dwFlags;
NI16 wShowWindow;
NI16 cbReserved2;
void* lpReserved2;
NI hStdInput;
NI hStdOutput;
NI hStdError;
};
struct tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg {
NI hProcess;
NI hThread;
NI32 dwProcessId;
NI32 dwThreadId;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
NI rootIdx;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI16 align;
NI16 depth;
NU32* display;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg {
  RootObj Sup;
NI fProcessHandle;
NI fThreadHandle;
int inHandle;
int outHandle;
int errHandle;
NI id;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* inStream;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* outStream;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* errStream;
int exitStatus;
NIM_BOOL exitFlag;
tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options;
};
struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ {
NI len;
NI cap;
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ {
NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {
tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ traceStack;
tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ toFree;
NI freed;
NI touched;
NI edges;
NI rcSum;
NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyUncheckedArray__72XmdLy0QAaMtx66AmNKfA[1];
typedef NU8 tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA;
struct tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw {
NI32 nLength;
void* lpSecurityDescriptor;
NI32 bInheritHandle;
};
typedef N_STDCALL_PTR(NI32, tyProc__C5kM33gEhlSKPXwfDNHofQ) (NI* hReadPipe__If9c59bJXpUW6ftqPc9bgVM9bg, NI* hWritePipe__wVyN9bgBTJdivpOmfIps9bHg, tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw* lpPipeAttributes__exRnZiU6OzUYSvIq7spRiA, NI32 nSize__WIPkjuiSosrzooRXxOahSg);
typedef N_STDCALL_PTR(NI32, tyProc__mBVOPXmpGfUrrbA9a5K9cMbQ) (NI hObject__3nsh2KDAVOt7pgJNF2oQZQ, NI32 dwMask__p81ZSgWkjKkefX9aMdKZnHQ, NI32 dwFlags__xmNSKK7xwzEASZOQ0zj60w);
typedef N_STDCALL_PTR(NI, tyProc__IDUPJnDaqrBXTB4aj79bKLg) (NI16* lpName__qfyXYoZgCJqgILgJ3vUFGw, NI32 dwOpenMode__xXGpr9ckmmSNv9bUBUc3KPIw, NI32 dwPipeMode__Xth4XLfMo6siiPXJktlU7w, NI32 nMaxInstances__2c5qceG8QnsnHbk2yqdzew, NI32 nOutBufferSize__Kcah3HEeVQcZ8UfftKphvA, NI32 nInBufferSize__KFIKj0mho2KIX4eWK9cToRg, NI32 nDefaultTimeOut__YqrGfvRFWAYQvoAUBWOWEg, tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw* lpSecurityAttributes__ClcIy9cf9b0xJ6SFuPauAWOQ);
typedef NI16 tyUncheckedArray__Tyd4y3haUOOHTj71TPIRag[1];
typedef N_STDCALL_PTR(NI, tyProc__Q9box9as0S1hHKH9cSO3MGDDA) (NI16* lpFileName__9ctvi9c9ctDS8vvvGb4u9cT0xw, NI32 dwDesiredAccess__KtwflmdHiZTCC67pJh7utw, NI32 dwShareMode__4lTKZeeZx8CO4sPfeloWag, void* lpSecurityAttributes__my8smoGuL9adyz8sS9c5eyvw, NI32 dwCreationDisposition__anf40ktzeGofEzevOorpSg, NI32 dwFlagsAndAttributes__p9afOa31WNAS1chD9bRBZcSQ, NI hTemplateFile__rLTaQS6GD1drnxaXjUHhEg);
typedef N_STDCALL_PTR(NI, tyProc__uryidYWkntM7ddjZSyxvyQ) (void);
typedef N_STDCALL_PTR(NI32, tyProc__oew1DfaGl5XhHmnBK0HYXQ) (NI hSourceProcessHandle__xyMwiBECbRkXsOqyuK6byw, NI hSourceHandle__8SfPVfcSRiEovrhXlnel7w, NI hTargetProcessHandle__BMHhJBZouiTUVMbKJjGRMw, NI* lpTargetHandle__rbkumC8A9aL9atye5PEuETOA, NI32 dwDesiredAccess__BJP3KfoB6vjkX0IjBhv7MA, NI32 bInheritHandle__MWCkl0Y9cv0wlz6URrh9bfYw, NI32 dwOptions__7TmbK9cX9aRKApZv2XtZPv4Q);
typedef N_STDCALL_PTR(NI32, tyProc__P13srMBg9b3d3yEV9aW4NCoA) (NI hObject__INxb1b9bZeFFXtDEsUaLIig);
typedef N_STDCALL_PTR(NI, tyProc__zP2zGemcuVRvOUE82f9a0Pw) (NI32 nStdHandle__WEmQ1DRpWPkca7bxtCMMlw);
struct tyTuple__0hEbbYmlam6yzyW5MFo9cjg {
NCSTRING Field0;
NI Field1;
};
struct tySequence__xv3aaFd3JCw8NbmALHiezQ {
  NI len; tySequence__xv3aaFd3JCw8NbmALHiezQ_Content* p;
};
typedef NU8 tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg {
  RootObj Sup;
NI counter;
tySequence__xv3aaFd3JCw8NbmALHiezQ data;
tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA {
NimStringV2 Field0;
NimStringV2 Field1;
NIM_BOOL Field2;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef N_STDCALL_PTR(NI32, tyProc__Ij9aBl82y9bf8kihDdsUvIEg) (NI16* lpApplicationName__pKvGGXpz7YorHOYkMWeiTA, NI16* lpCommandLine__KeODVOPSzd8hOzeKYXykfA, tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw* lpProcessAttributes__Mt5mRoa8F9cVFhYthLdyL9cQ, tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw* lpThreadAttributes__DLrpE8d9cYmBrK74zHgrg9bg, NI32 bInheritHandles__76MvmVFboq3f8ZcprJSwcQ, NI32 dwCreationFlags__A7yaYDK69b7RHk7yqO07r0g, NI16* lpEnvironment__rW49aPITYA3JFgnmLk9bcE0g, NI16* lpCurrentDirectory__gMhy9c0UxN38yMqlwRWXFEw, tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ* lpStartupInfo__u67ejp6exXkl1yLKPE6dBA, tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg* lpProcessInformation__hPPCtwI19cTtKRf9bPCLnQng);
typedef N_NIMCALL_PTR(void, tyProc__JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA_2);
typedef N_NIMCALL_PTR(void, tyProc__3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA_3, NI pos__r6hw59beE9aoqvlZE89czGAoA);
typedef N_NIMCALL_PTR(NI, tyProc__xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA_4);
typedef N_NIMCALL_PTR(NI, tyProc__c9c0f59ak4YGQ6neEym8LPKw) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA_5, NimStringV2* buffer__PM9cBMwTIkpmCjD9bBqlsOzA, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA slice__LflnlnJtEFxGJh6kkpBT8Q);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__7jFfqMk9ajToCz6Hv9atCA4A) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA_6, NimStringV2* line__l0JXwD1b16Rd4reRwHORCg);
typedef N_NIMCALL_PTR(NI, tyProc__2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA_7, void* buffer__PM9cBMwTIkpmCjD9bBqlsOzA_2, NI bufLen__C9aEgsn2u7i83Z9ch1H9cMwow);
typedef N_NIMCALL_PTR(void, tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__ACoCnU9bMD44cvwlDY4pIOA_8, void* buffer__PM9cBMwTIkpmCjD9bBqlsOzA_3, NI bufLen__C9aEgsn2u7i83Z9ch1H9cMwow_2);
struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ {
  RootObj Sup;
tyProc__JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc__9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc__3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc__xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc__c9c0f59ak4YGQ6neEym8LPKw readDataStrImpl;
tyProc__7jFfqMk9ajToCz6Hv9atCA4A readLineImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc__JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
struct tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ {
  tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ Sup;
NI handle;
NIM_BOOL atTheEnd;
};
typedef N_STDCALL_PTR(NI32, tyProc__9ajZYMGL5GqiRFqiCC367oA) (NI hFile__be2p0EfhLKpRVSiIM2fxQg, void* buffer__Yn2KJiW9cvpZeDEGMYMUPhQ, NI32 nNumberOfBytesToRead__eYd9a9arCo1fY9cDwXKcs0pOw, NI32* lpNumberOfBytesRead__T0eQGW8cVkQJI9cYtfwOPdA, void* lpOverlapped__qHKDTJqHww9bI456oYeWpTw);
typedef N_STDCALL_PTR(NI32, tyProc__FprzxJFfqQdWyyGxiUsmeQ) (NI hHandle__vkay13PRkF6AS3NADri3cA, NI32 dwMilliseconds__G9bScDx1MD4fsah3lADZmqg);
typedef N_STDCALL_PTR(NI32, tyProc__7S2vVNF4dlY59blFohNWnHg) (NI hProcess__RSc8Zp9avgRZdOsMFMhG9arA, NI uExitCode__9b11jNFYruORcKYmTvv9cwwQ);
typedef N_STDCALL_PTR(NI32, tyProc__KxeGXN001TReCr89ca9c5bng) (NI hProcess__22ACiTHgBADh2KGsWreaCg, NI32* lpExitCode__JSVic5Q0UgEwPWJmDQubkA);
struct tyTuple__XOVT24GHXwqiEj5GCsEGCA {
NimStringV2 Field0;
NI Field1;
};
typedef NimStringV2 tyArray__8ZvwQIddfpj2THRVPsFzIQ[1];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI idx__TmarJVy1bBUGjuYQG3Rvcg, void* ClE_0);
void* ClE_0;
} tyProc__SqRJqa5aOiKB4EuKlKh9asA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI idx__TmarJVy1bBUGjuYQG3Rvcg_2, tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__Df32j9cooi2GQZP8n9cyRg4A, void* ClE_0);
void* ClE_0;
} tyProc__oudJckli4GdxAXLVzBBlAw;
struct tySequence__PrBYolTs4TOSgE8v5oqDUQ {
  NI len; tySequence__PrBYolTs4TOSgE8v5oqDUQ_Content* p;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
typedef NI tyArray__SLBTEB08vk46ttuRaTxAYw[64];
typedef N_CLOSURE_PTR(void, TM__HZdw8BhppcTQo8DIK46LSg_31) (NI idx__TmarJVy1bBUGjuYQG3Rvcg);
typedef N_STDCALL_PTR(NI32, tyProc__Dx0emMHXXGxkRnYGUaFLbg) (NI32 nCount__zkW9b9axavGVHjAnx8023sHA, NI* lpHandles__9byOChVr7vEZmjfUr9bzrPPw, NI32 bWaitAll__RwTniaJCRmGoXJPuv4dAQg, NI32 dwMilliseconds__kGN4q36p0BpcOzPllJ9b6ag);
typedef N_CLOSURE_PTR(void, TM__HZdw8BhppcTQo8DIK46LSg_35) (NI idx__TmarJVy1bBUGjuYQG3Rvcg_2, tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__Df32j9cooi2GQZP8n9cyRg4A);
typedef N_CLOSURE_PTR(void, TM__HZdw8BhppcTQo8DIK46LSg_36) (NI idx__TmarJVy1bBUGjuYQG3Rvcg);
typedef N_CLOSURE_PTR(void, TM__HZdw8BhppcTQo8DIK46LSg_38) (NI idx__TmarJVy1bBUGjuYQG3Rvcg);
typedef N_CLOSURE_PTR(void, TM__HZdw8BhppcTQo8DIK46LSg_40) (NI idx__TmarJVy1bBUGjuYQG3Rvcg_2, tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__Df32j9cooi2GQZP8n9cyRg4A);


#ifndef tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
#define tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content { NI cap; tyTuple__sPaDkVPSC0MkcoXCxPH9ccA data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};


#ifndef tySequence__PrBYolTs4TOSgE8v5oqDUQ_Content_PP
#define tySequence__PrBYolTs4TOSgE8v5oqDUQ_Content_PP
struct tySequence__PrBYolTs4TOSgE8v5oqDUQ_Content { NI cap; tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
#define tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_206)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg** dest__wO8y9aLM5jbMyT4Eh0U2FHw);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p__dABzUdgzrkaSDMDdaWLtRg);
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3141)(NIM_BOOL isDestroyAction__wlZkTmY2exyvD4PmYZgCHw, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s__rifrsJGbWaDLWZRj0ktOnA, TNimTypeV2* desc__YB9c2fwKemzor6iGIpZW9bIw);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p__9avvNwjq1NdQwdCBwEYwA9bw);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size__LZn6dneMVUSD9cVJcoc7Slw, NI alignment__eu9b1Xf7SGvOM5v8REyXVWA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_219)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest__wO8y9aLM5jbMyT4Eh0U2FHw_2);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZosproc_228)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest__kJ2JTcs52CZxTTxbKybYhA, void* env__qTBFBzpD5BlMw0JzXovSqQ);
static N_INLINE(void, nimTraceRefDyn)(void* q__DU69bA8QWYzcJYHZK62MWjA, void* env__jq9cK8cvI9c0aQFP3P6pQbYA);
static N_INLINE(void, add__system_2686)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s__G58rBzp9arUs2Le3q9bajUHA, void** c__glbQoed0fMuhXSt1wQUc7w, TNimTypeV2* t__afUUWAFqIJFXIEkjClESEA);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_1735)(NI size__uYg0s4J9bHgDzPf7XJS2y2Q);
static N_INLINE(void, copyMem__system_1719)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p__1Ef17pd0N75MzUBHEC131Q);
N_LIB_PRIVATE N_NIMCALL(void, createPipeHandles__pureZosproc_787)(NI* rdHandle__9cp9b85uaeOob4jZ8x4sriSg, NI* wrHandle__INjCMvaPmnehebHrtAse4g);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_86)(NI32 errorCode__pW4c9aJEinlYI1jZIvhGnmw, NimStringV2 additionalInfo__B0aylqmo75KM1PZjhD2Ciw);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_89)(void);
N_LIB_PRIVATE N_NIMCALL(void, createAllPipeHandles__pureZosproc_752)(tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ* si__uHsrFtUO7Mk8hzPp0nZ3Xw, NI* stdin__dS1b8X9bn6dC2ZZEWgAQb5Q, NI* stdout__dMYgA6WVZinWKi8dINL9bBQ, NI* stderr__9b2E9b3wEAndYKpn06YaEfdw, NI hash__CyihWfzmJf4fwR167xo9a1g);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__stdZwidestrs_287)(NimStringV2 s__TvPuMx6CGjgZlMxAat9b5Ug);
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_3)(NI x__KsYCTjO9co8rDpst8JJ2TVg);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space__9cQ1OhOryhnk7At3WzUsjtA);
static N_INLINE(NI16*, toWideCString__stdZwidestrs_41)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A x__NBa1pzleDFoqbT7nhVpSnA);
N_LIB_PRIVATE N_NIMCALL(NI, myDup__pureZosproc_747)(NI h__S2rQc3INEGKmVZADhb6nEA, NI32 inherit__FR8RLZpzOAjVKFfPsMLReA);
static N_INLINE(void, closeHandleCheck__pureZosproc_636)(NI handle__lZgeRC9bkpgXPCN5FzTczAg);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_13)(NimStringV2* dest__C2JKGPCNdWKCPrsQvNywTQ);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZwidestrs_6)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A* a__T5KnFC1i1GXKLoRVEXa5DA);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s__UF7MRy5Ww0D3yXFWtooEkw);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, buildCommandLine__pureZosproc_701)(NimStringV2 a__pmQrz1ISnmaN3vcvT74Zng, NimStringV2* args__XBJwvQ3N3ZpFtigVv9aDo3w, NI args__XBJwvQ3N3ZpFtigVv9aDo3wLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nospquoteShell)(NimStringV2 s__1LWv1m0YwP4NTCOIOrbMPw);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s__S65jkNxJ72wMzHX9bQ0it8w, NIM_CHAR c__q53woDK9bF1K5bAKmsVpSkA);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s__qL2AkrAohOvo9bZZC15G6TA, NI addlen__uGPPC8Yor9a9avOoki7IG3AQ);
N_LIB_PRIVATE N_NIMCALL(tyTuple__0hEbbYmlam6yzyW5MFo9cjg, buildEnv__pureZosproc_713)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* env__EZMLnBFjz0ylido4MSOE4A);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZassertions_16)(NimStringV2* dest__9bysEU1F6xjkB13t7jg7tFg, NimStringV2 src__Q0EcxC6eCjA9adTTWfOBbQQ);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_1737)(NI size__4KerptJEDen31kAmPf36WQ);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str__1hBypH3GHj7R9aGZBu1HZPg);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args__vU9bPv9cuTwXcj2blBSnzjTw, NI args__vU9bPv9cuTwXcj2blBSnzjTwLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__stdZwidestrs_281)(NCSTRING s__TvPuMx6CGjgZlMxAat9b5Ug);
N_LIB_PRIVATE N_NIMCALL(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A, newWideCString__stdZwidestrs_260)(NCSTRING source__5gss6ZWNkeeJWSOYkl9b9b0A, NI L__Tptnj2Di3UrhHTp6kEz7Zg);
static N_INLINE(void, fileClose__pureZosproc_643)(NI* h__5W9bedCO9agnTYBS7PJaxP4g);
static N_INLINE(NIM_BOOL, eqeq___system_7539)(NCSTRING x__Z3lojyrZeeORXB9aFmHlS7w, NCSTRING y__SlnicWIZiUaUC9cl2PfooTA);
N_LIB_PRIVATE N_NIMCALL(void, nospclose)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__WsqIZlX7CGSPiON9am13V9aw);
static N_INLINE(void, fileClose__pureZosproc_929)(int* h__5W9bedCO9agnTYBS7PJaxP4g_2);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_58)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__qYFvro9cLG9by9cSabBsxwxpA);
N_LIB_PRIVATE N_NIMCALL(void, closeThreadAndProcessHandle__pureZosproc_917)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__i0Khfx3LaRvZjWf5mMrbng);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatSingleElem)(NimStringV2 formatstr__j8zBuAo4g9aa9a49cWV9b6hTgw_2, NimStringV2 a__oIwfPiaKNIKCHjM11VCkjw_2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZstreams_620)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ** dest__9b8cXPDCgvJLiCsxndj9cYvw, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* src__GARjKEzrpU7Z3Ptc09bj9a3w);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ*, newFileHandleStream__pureZosproc_695)(NI handle__oHkPLB9axgGQ9cxQu9biOR9aNw);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_646)(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ** dest__wO8y9aLM5jbMyT4Eh0U2FHw_3);
N_LIB_PRIVATE N_NIMCALL(void, hsClose__pureZosproc_641)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__jwdr0iZTC7EhOUl1b6sKUA);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hsAtEnd__pureZosproc_677)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__Q9abPn9bfJx9cdeCyy7jzNtjg);
N_LIB_PRIVATE N_NIMCALL(NI, hsReadData__pureZosproc_680)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__LkmFLRyQRfFgkFiRuysVAw, void* buffer__02lNwaDQknHCXR2VdqOD4w, NI bufLen__b0n9bSUu1R9aCv7tugzsabMg);
N_LIB_PRIVATE N_NIMCALL(void, hsWriteData__pureZosproc_688)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__Go9cytw9cKc4d29ctlEiZa8gQ, void* buffer__E8jpWqJ11Ij9atIWxGivFnA, NI bufLen__7hH1SdmRNKtBuKKYSCas9cQ);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstreams_616)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ** dest__UR7eUPUKn59cgUFb9csNd7DQ, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* src__P4co8QvsVH1kTz4sfKnhTw, NIM_BOOL cyclic__kknf9cfhePxJk7ZDUgotYiA);
N_LIB_PRIVATE N_NIMCALL(void, nospterminate)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__PDEn8aci3oMM5ysYVh9asAQ);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosprunning)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__EMbBqhuu9aDwmVfDAhHNsjw);
N_LIB_PRIVATE N_NIMCALL(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg*, nospstartProcess)(NimStringV2 command__td0V6TIK9bkKmaFJWeVBaVA, NimStringV2 workingDir__5SDamHy49cOhPaAsmtOC63A, NimStringV2* args__OqKG9b6auqqw28FSytKfUWA, NI args__OqKG9b6auqqw28FSytKfUWALen_0, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* env__sV8uELyKNv4uoi3EYenWzg, tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options__gEn0pKixzTB9a2na0EDA0vQ);
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*, nospoutputStream)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__qaL4brv79ac69aLBwudCF4VQ);
N_LIB_PRIVATE N_NIMCALL(void, write__pureZstreams_184)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__fKu7O5cltI6TPtzZVoVQrg, NimStringV2 x__ox6V2s6YITKXHQW7rjBaTQ);
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*, nospinputStream)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__cewAKsIlXrf47EwbijyVdA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_613)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ** dest__0PMdyEYBvd5YCiye8xqdOw);
N_NIMCALL(NimStringV2, rawNewString)(NI cap__aiFqe9bSUp1HPQPsLukio0A);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine__pureZstreams_543)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__MyFqhYniThlpRnt4Gf4hLg, NimStringV2* line__OeJ9cWkqD3bw15msR8vOWxA);
N_LIB_PRIVATE N_NIMCALL(NI, nosppeekExitCode)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__BdpVZkdOF4TjY3Vnu5hsOw);
N_LIB_PRIVATE N_NIMCALL(NI, ncpicountProcessors)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__PrBYolTs4TOSgE8v5oqDUQ, newSeq__pureZosproc_267)(NI len__p49b9b5HIylhMqZoxjxlq7QA);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g, newSeq__pureZosproc_398)(NI len__p49b9b5HIylhMqZoxjxlq7QA_2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZosproc_213)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg** dest__aDT2vBnQ9bz4A0OSp9cSE9aNA, tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* src__UGcAo9cTo1ajuY9aMQsdbGqA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_406)(tySequence__qwqHTkRvwhrRyENtudHQ7g* dest__roU2YOy9a9a9beBr400TJtMRA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_275)(tySequence__PrBYolTs4TOSgE8v5oqDUQ* dest__roU2YOy9a9a9beBr400TJtMRA);
N_LIB_PRIVATE N_NIMCALL(NI, nospwaitForExit)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__hUK4B8yW50r9ar7GPvflLQA, NI timeout__DDDS0NJhst3CHPYe2zkz4Q);
N_LIB_PRIVATE TNimTypeV2 NTIv2__2rGNQnv9bU4hanI2g3svReg_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__HZdw8BhppcTQo8DIK46LSg_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_4 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_5 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_6 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_7 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__HZdw8BhppcTQo8DIK46LSg_8 = { 15 | NIM_STRLIT_FLAG, "\\\\.\\pipe\\stdout" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_9 = {15, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_8};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__HZdw8BhppcTQo8DIK46LSg_10 = { 14 | NIM_STRLIT_FLAG, "\\\\.\\pipe\\stdin" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_11 = {14, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_10};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_12 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_13 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_14 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_15 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_16 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_17 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__HZdw8BhppcTQo8DIK46LSg_19 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_20 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_19};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__HZdw8BhppcTQo8DIK46LSg_21 = { 44 | NIM_STRLIT_FLAG, "Requested command not found: \'$1\'. OS error:" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_22 = {44, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_21};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Uwf6VGZy4JPKquxCiOCalQ_;
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_24 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_25 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_26 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__HZdw8BhppcTQo8DIK46LSg_27 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_28 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_27};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_29 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static NIM_CONST tyProc__SqRJqa5aOiKB4EuKlKh9asA TM__HZdw8BhppcTQo8DIK46LSg_30 = {NIM_NIL,NIM_NIL};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_32 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_33 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static NIM_CONST tyProc__oudJckli4GdxAXLVzBBlAw TM__HZdw8BhppcTQo8DIK46LSg_34 = {NIM_NIL,NIM_NIL};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_37 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_39 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_3};
static NIM_CONST tyTuple__0hEbbYmlam6yzyW5MFo9cjg TM__HZdw8BhppcTQo8DIK46LSg_18 = {((NCSTRING) NIM_NIL),
((NI)-1)}
;
extern NIM_BOOL nimInErrorMode__system_3980;
static NIM_CONST NU32 TM__HZdw8BhppcTQo8DIK46LSg_2[2] = {3701606400, 2978824704};
N_LIB_PRIVATE TNimTypeV2 NTIv2__2rGNQnv9bU4hanI2g3svReg_ = {.destructor = (void*)eqdestroy___pureZosproc_219, .size = sizeof(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg), .align = (NI16) NIM_ALIGNOF(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg), .depth = 1, .display = TM__HZdw8BhppcTQo8DIK46LSg_2, .traceImpl = (void*)eqtrace___pureZosproc_228, .flags = 0};
extern tyProc__C5kM33gEhlSKPXwfDNHofQ Dl_1442840696_;
extern tyProc__mBVOPXmpGfUrrbA9a5K9cMbQ Dl_1442841175_;
extern tyProc__IDUPJnDaqrBXTB4aj79bKLg Dl_1442840701_;
extern tyProc__Q9box9as0S1hHKH9cSO3MGDDA Dl_1442841180_;
extern tyProc__uryidYWkntM7ddjZSyxvyQ Dl_1442841179_;
extern tyProc__oew1DfaGl5XhHmnBK0HYXQ Dl_1442841164_;
extern tyProc__P13srMBg9b3d3yEV9aW4NCoA Dl_1442840682_;
extern tyProc__zP2zGemcuVRvOUE82f9a0Pw Dl_1442840741_;
extern tyProc__Ij9aBl82y9bf8kihDdsUvIEg Dl_1442840717_;
static NIM_CONST NU32 TM__HZdw8BhppcTQo8DIK46LSg_23[3] = {3701606400, 1981855744, 133846016};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Uwf6VGZy4JPKquxCiOCalQ_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ), .align = (NI16) NIM_ALIGNOF(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ), .depth = 2, .display = TM__HZdw8BhppcTQo8DIK46LSg_23, .traceImpl = (void*)NIM_NIL, .flags = 0};
extern tyProc__9ajZYMGL5GqiRFqiCC367oA Dl_1442840684_;
extern tyProc__9ajZYMGL5GqiRFqiCC367oA Dl_1442840690_;
extern tyProc__FprzxJFfqQdWyyGxiUsmeQ Dl_1442840732_;
extern tyProc__7S2vVNF4dlY59blFohNWnHg Dl_1442840735_;
extern tyProc__KxeGXN001TReCr89ca9c5bng Dl_1442840738_;
extern tyProc__Dx0emMHXXGxkRnYGUaFLbg Dl_1442841126_;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a__tZiCJHYy5dYyAh9cxwrrVhQ, v__iM7JOvZxArJIvbhGyRZG6Q, ((size_t) (size__ntsFNLS0mpvnjQFrZT7DCw)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3980);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p__BuPKoq7dppy2upaj3KUaxw, ((int)0), size__ttWVm79bajRU3tarcA7MkLw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x__nhqJNug5PDvy9ah8vc6uJ5Q))) - (NU32)(((NU) (y__LJLJ0MGnpTb2U2nvMvG6MQ))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p__dABzUdgzrkaSDMDdaWLtRg) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p__dABzUdgzrkaSDMDdaWLtRg == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_790(((NI) (ptrdiff_t) (p__dABzUdgzrkaSDMDdaWLtRg)), ((NI)8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI)16);
		}
		LA6_: ;
		rememberCycle__system_3141(result, cell, (*((TNimTypeV2**) (p__dABzUdgzrkaSDMDdaWLtRg))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_206)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg** dest__wO8y9aLM5jbMyT4Eh0U2FHw) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest__wO8y9aLM5jbMyT4Eh0U2FHw));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__wO8y9aLM5jbMyT4Eh0U2FHw));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_219)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest__wO8y9aLM5jbMyT4Eh0U2FHw_2) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_2).inStream);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_2).inStream);
	}
	LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_2).outStream);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_2).outStream);
	}
	LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_2).errStream);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_2).errStream);
	}
	LA14_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));
}
static N_INLINE(void, copyMem__system_1719)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}
static N_INLINE(void, add__system_2686)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s__G58rBzp9arUs2Le3q9bajUHA, void** c__glbQoed0fMuhXSt1wQUc7w, TNimTypeV2* t__afUUWAFqIJFXIEkjClESEA) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	{
		tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
		void* T5_;
		if (!((*s__G58rBzp9arUs2Le3q9bajUHA).cap <= (*s__G58rBzp9arUs2Le3q9bajUHA).len)) goto LA3_;
		(*s__G58rBzp9arUs2Le3q9bajUHA).cap = (NI)((NI)((*s__G58rBzp9arUs2Le3q9bajUHA).cap * ((NI)3)) / ((NI)2));
		T5_ = (void*)0;
		T5_ = allocImpl__system_1735(((NI) ((NI)((*s__G58rBzp9arUs2Le3q9bajUHA).cap * ((NI)8)))));
		d = ((tyTuple__N4J9cV4JZGem3ljqqj5rT0Q*) (T5_));
		copyMem__system_1719(((void*) (d)), ((void*) ((*s__G58rBzp9arUs2Le3q9bajUHA).d)), ((NI) ((NI)((*s__G58rBzp9arUs2Le3q9bajUHA).len * ((NI)8)))));
		dealloc(((void*) ((*s__G58rBzp9arUs2Le3q9bajUHA).d)));
		(*s__G58rBzp9arUs2Le3q9bajUHA).d = d;
	}
	LA3_: ;
	colontmp_ = c__glbQoed0fMuhXSt1wQUc7w;
	colontmp__2 = t__afUUWAFqIJFXIEkjClESEA;
	(*s__G58rBzp9arUs2Le3q9bajUHA).d[(*s__G58rBzp9arUs2Le3q9bajUHA).len].Field0 = colontmp_;
	(*s__G58rBzp9arUs2Le3q9bajUHA).d[(*s__G58rBzp9arUs2Le3q9bajUHA).len].Field1 = colontmp__2;
	(*s__G58rBzp9arUs2Le3q9bajUHA).len += ((NI)1);
}
static N_INLINE(void, nimTraceRefDyn)(void* q__DU69bA8QWYzcJYHZK62MWjA, void* env__jq9cK8cvI9c0aQFP3P6pQbYA) {
	void** p;
	p = ((void**) (q__DU69bA8QWYzcJYHZK62MWjA));
	{
		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;
		if (!!(((*p) == NIM_NIL))) goto LA3_;
		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env__jq9cK8cvI9c0aQFP3P6pQbYA));
		add__system_2686((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZosproc_228)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest__kJ2JTcs52CZxTTxbKybYhA, void* env__qTBFBzpD5BlMw0JzXovSqQ) {
	nimTraceRefDyn(&(*dest__kJ2JTcs52CZxTTxbKybYhA).inStream, env__qTBFBzpD5BlMw0JzXovSqQ);
	nimTraceRefDyn(&(*dest__kJ2JTcs52CZxTTxbKybYhA).outStream, env__qTBFBzpD5BlMw0JzXovSqQ);
	nimTraceRefDyn(&(*dest__kJ2JTcs52CZxTTxbKybYhA).errStream, env__qTBFBzpD5BlMw0JzXovSqQ);
}
N_LIB_PRIVATE N_NIMCALL(void, createPipeHandles__pureZosproc_787)(NI* rdHandle__9cp9b85uaeOob4jZ8x4sriSg, NI* wrHandle__INjCMvaPmnehebHrtAse4g) {
	tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw sa;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&sa), sizeof(tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw));
	sa.nLength = ((int)12);
	sa.lpSecurityDescriptor = NIM_NIL;
	sa.bInheritHandle = ((NI32)1);
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_1442840696_(rdHandle__9cp9b85uaeOob4jZ8x4sriSg, wrHandle__INjCMvaPmnehebHrtAse4g, (&sa), ((NI32)0));
		if (!(T3_ == ((NI32)0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_86(T6_, TM__HZdw8BhppcTQo8DIK46LSg_4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g) {
	{
		if (!(((NI)0) < src__369aqaoei6FUsRf9cDAsKQ2g.len)) goto LA3_;
		copyMem__system_1719(((void*) ((&(*(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).p).data[(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len]))), ((void*) ((&(*src__369aqaoei6FUsRf9cDAsKQ2g.p).data[((NI)0)]))), ((NI) ((NI)(src__369aqaoei6FUsRf9cDAsKQ2g.len + ((NI)1)))));
		(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len += src__369aqaoei6FUsRf9cDAsKQ2g.len;
	}
	LA3_: ;
}
static N_INLINE(NI16*, toWideCString__stdZwidestrs_41)(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A x__NBa1pzleDFoqbT7nhVpSnA) {
	NI16* result;
	result = (NI16*)0;
	result = x__NBa1pzleDFoqbT7nhVpSnA.data;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, myDup__pureZosproc_747)(NI h__S2rQc3INEGKmVZADhb6nEA, NI32 inherit__FR8RLZpzOAjVKFfPsMLReA) {
	NI result;
	NI thisProc;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	thisProc = Dl_1442841179_();
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_1442841164_(thisProc, h__S2rQc3INEGKmVZADhb6nEA, thisProc, (&result), ((NI32)0), inherit__FR8RLZpzOAjVKFfPsMLReA, ((NI32)2));
		if (!(T3_ == ((NI32)0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_86(T6_, TM__HZdw8BhppcTQo8DIK46LSg_15);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, closeHandleCheck__pureZosproc_636)(NI handle__lZgeRC9bkpgXPCN5FzTczAg) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI32 T3_;
		NI32 T6_;
		T3_ = (NI32)0;
		T3_ = Dl_1442840682_(handle__lZgeRC9bkpgXPCN5FzTczAg);
		if (!(T3_ == ((NI32)0))) goto LA4_;
		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_86(T6_, TM__HZdw8BhppcTQo8DIK46LSg_17);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, createAllPipeHandles__pureZosproc_752)(tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ* si__uHsrFtUO7Mk8hzPp0nZ3Xw, NI* stdin__dS1b8X9bn6dC2ZZEWgAQb5Q, NI* stdout__dMYgA6WVZinWKi8dINL9bBQ, NI* stderr__9b2E9b3wEAndYKpn06YaEfdw, NI hash__CyihWfzmJf4fwR167xo9a1g) {
	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A pipeOutName;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A pipeInName;
	NimStringV2 colontmpD__3;
	NimStringV2 colontmpD__4;
	tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw sa;
	NimStringV2 T2_;
	NimStringV2 T3_;
	NI pipeOut;
	NI16* T4_;
	NI pipeIn;
	NI16* T10_;
	NI16* T16_;
	NI T22_;
	NI16* T23_;
	NI T29_;
	NI T30_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&pipeOutName), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimZeroMem((void*)(&pipeInName), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
	nimZeroMem((void*)(&sa), sizeof(tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw));
	sa.nLength = ((int)12);
	sa.lpSecurityDescriptor = NIM_NIL;
	sa.bInheritHandle = ((NI32)1);
	T2_.len = 0; T2_.p = NIM_NIL;
	colontmpD_ = dollar___systemZdollars_3(hash__CyihWfzmJf4fwR167xo9a1g);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = rawNewString(colontmpD_.len + 15);
appendString((&T2_), TM__HZdw8BhppcTQo8DIK46LSg_9);
appendString((&T2_), colontmpD_);
	colontmpD__2 = T2_;
	pipeOutName = newWideCString__stdZwidestrs_287(colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_.len = 0; T3_.p = NIM_NIL;
	colontmpD__3 = dollar___systemZdollars_3(hash__CyihWfzmJf4fwR167xo9a1g);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = rawNewString(colontmpD__3.len + 14);
appendString((&T3_), TM__HZdw8BhppcTQo8DIK46LSg_11);
appendString((&T3_), colontmpD__3);
	colontmpD__4 = T3_;
	pipeInName = newWideCString__stdZwidestrs_287(colontmpD__4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T4_ = (NI16*)0;
	T4_ = toWideCString__stdZwidestrs_41(pipeOutName);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	pipeOut = Dl_1442840701_(T4_, ((NI32)-2147483647), ((NI32)1), ((NI32)1), ((NI32)1024), ((NI32)1024), ((NI32)0), (&sa));
	{
		NI32 T9_;
		if (!(pipeOut == ((NI)-1))) goto LA7_;
		T9_ = (NI32)0;
		T9_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_86(T9_, TM__HZdw8BhppcTQo8DIK46LSg_12);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA7_: ;
	T10_ = (NI16*)0;
	T10_ = toWideCString__stdZwidestrs_41(pipeInName);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	pipeIn = Dl_1442840701_(T10_, ((NI32)-2147483646), ((NI32)1), ((NI32)1), ((NI32)1024), ((NI32)1024), ((NI32)0), (&sa));
	{
		NI32 T15_;
		if (!(pipeIn == ((NI)-1))) goto LA13_;
		T15_ = (NI32)0;
		T15_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_86(T15_, TM__HZdw8BhppcTQo8DIK46LSg_13);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA13_: ;
	T16_ = (NI16*)0;
	T16_ = toWideCString__stdZwidestrs_41(pipeOutName);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*si__uHsrFtUO7Mk8hzPp0nZ3Xw).hStdOutput = Dl_1442841180_(T16_, ((NI32)1048578), ((NI32)0), ((void*) ((&sa))), ((NI32)3), ((NI32)128), ((NI)0));
	{
		NI32 T21_;
		if (!((*si__uHsrFtUO7Mk8hzPp0nZ3Xw).hStdOutput == ((NI)-1))) goto LA19_;
		T21_ = (NI32)0;
		T21_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_86(T21_, TM__HZdw8BhppcTQo8DIK46LSg_14);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA19_: ;
	T22_ = (NI)0;
	T22_ = myDup__pureZosproc_747((*si__uHsrFtUO7Mk8hzPp0nZ3Xw).hStdOutput, ((NI32)1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*si__uHsrFtUO7Mk8hzPp0nZ3Xw).hStdError = T22_;
	T23_ = (NI16*)0;
	T23_ = toWideCString__stdZwidestrs_41(pipeInName);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*si__uHsrFtUO7Mk8hzPp0nZ3Xw).hStdInput = Dl_1442841180_(T23_, ((NI32)1048577), ((NI32)0), ((void*) ((&sa))), ((NI32)3), ((NI32)128), ((NI)0));
	{
		NI32 T28_;
		if (!((*si__uHsrFtUO7Mk8hzPp0nZ3Xw).hStdInput == ((NI)-1))) goto LA26_;
		T28_ = (NI32)0;
		T28_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_86(T28_, TM__HZdw8BhppcTQo8DIK46LSg_16);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA26_: ;
	T29_ = (NI)0;
	T29_ = myDup__pureZosproc_747(pipeIn, ((NI32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*stdin__dS1b8X9bn6dC2ZZEWgAQb5Q) = T29_;
	T30_ = (NI)0;
	T30_ = myDup__pureZosproc_747(pipeOut, ((NI32)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*stdout__dMYgA6WVZinWKi8dINL9bBQ) = T30_;
	closeHandleCheck__pureZosproc_636(pipeIn);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	closeHandleCheck__pureZosproc_636(pipeOut);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	(*stderr__9b2E9b3wEAndYKpn06YaEfdw) = (*stdout__dMYgA6WVZinWKi8dINL9bBQ);
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZassertions_13((&colontmpD__4));
		eqdestroy___stdZassertions_13((&colontmpD__3));
		eqdestroy___stdZwidestrs_6((&pipeInName));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___stdZassertions_13((&colontmpD__2));
		eqdestroy___stdZassertions_13((&colontmpD_));
		eqdestroy___stdZwidestrs_6((&pipeOutName));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s__UF7MRy5Ww0D3yXFWtooEkw) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s__UF7MRy5Ww0D3yXFWtooEkw.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s__UF7MRy5Ww0D3yXFWtooEkw.p).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s__S65jkNxJ72wMzHX9bQ0it8w, NIM_CHAR c__q53woDK9bF1K5bAKmsVpSkA) {
	prepareAdd(s__S65jkNxJ72wMzHX9bQ0it8w, ((NI)1));
	(*(*s__S65jkNxJ72wMzHX9bQ0it8w).p).data[(*s__S65jkNxJ72wMzHX9bQ0it8w).len] = c__q53woDK9bF1K5bAKmsVpSkA;
	(*(*s__S65jkNxJ72wMzHX9bQ0it8w).p).data[(NI)((*s__S65jkNxJ72wMzHX9bQ0it8w).len + ((NI)1))] = 0;
	(*s__S65jkNxJ72wMzHX9bQ0it8w).len += ((NI)1);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, buildCommandLine__pureZosproc_701)(NimStringV2 a__pmQrz1ISnmaN3vcvT74Zng, NimStringV2* args__XBJwvQ3N3ZpFtigVv9aDo3w, NI args__XBJwvQ3N3ZpFtigVv9aDo3wLen_0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = nospquoteShell(a__pmQrz1ISnmaN3vcvT74Zng);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (args__XBJwvQ3N3ZpFtigVv9aDo3wLen_0-1);
		res = ((NI)0);
		{
			while (1) {
				NimStringV2 colontmpD_;
				if (!(res <= colontmp_)) goto LA3				;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				i = res;
				nimAddCharV1((&result), 32);
				colontmpD_ = nospquoteShell(args__XBJwvQ3N3ZpFtigVv9aDo3w[i]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				prepareAdd((&result), colontmpD_.len + 0);
appendString((&result), colontmpD_);
				res += ((NI)1);
				eqdestroy___stdZassertions_13((&colontmpD_));
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__0hEbbYmlam6yzyW5MFo9cjg, buildEnv__pureZosproc_713)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* env__EZMLnBFjz0ylido4MSOE4A) {
	tyTuple__0hEbbYmlam6yzyW5MFo9cjg result;
	NI L;
	NCSTRING str;
	void* T10_;
	nimZeroMem((void*)(&result), sizeof(tyTuple__0hEbbYmlam6yzyW5MFo9cjg));
	L = ((NI)0);
	{
		NimStringV2 key;
		NimStringV2 val;
		key.len = 0; key.p = NIM_NIL;
		val.len = 0; val.p = NIM_NIL;
		{
			NI h;
			NI colontmp_;
			NI T3_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			T3_ = ((*env__EZMLnBFjz0ylido4MSOE4A).data.len-1);
			colontmp_ = T3_;
			res = ((NI)0);
			{
				while (1) {
					if (!(res <= colontmp_)) goto LA5					;
					h = res;
					{
						if (!(*env__EZMLnBFjz0ylido4MSOE4A).data.p->data[h].Field2) goto LA8_;
						eqcopy___stdZassertions_16((&key), (*env__EZMLnBFjz0ylido4MSOE4A).data.p->data[h].Field0);
						eqcopy___stdZassertions_16((&val), (*env__EZMLnBFjz0ylido4MSOE4A).data.p->data[h].Field1);
						L += (NI)((NI)(key.len + val.len) + ((NI)2));
					}
					LA8_: ;
					res += ((NI)1);
				} LA5: ;
			}
		}
		eqdestroy___stdZassertions_13((&val));
		eqdestroy___stdZassertions_13((&key));
	}
	T10_ = (void*)0;
	T10_ = alloc0Impl__system_1737(((NI) ((NI)(L + ((NI)2)))));
	str = ((NCSTRING) (T10_));
	L = ((NI)0);
	{
		NimStringV2 key_2;
		NimStringV2 val_2;
		key_2.len = 0; key_2.p = NIM_NIL;
		val_2.len = 0; val_2.p = NIM_NIL;
		{
			NI h_2;
			NI colontmp__2;
			NI T13_;
			NI res_2;
			h_2 = (NI)0;
			colontmp__2 = (NI)0;
			T13_ = ((*env__EZMLnBFjz0ylido4MSOE4A).data.len-1);
			colontmp__2 = T13_;
			res_2 = ((NI)0);
			{
				while (1) {
					if (!(res_2 <= colontmp__2)) goto LA15					;
					h_2 = res_2;
					{
						NimStringV2 x;
						NimStringV2 T20_;
						if (!(*env__EZMLnBFjz0ylido4MSOE4A).data.p->data[h_2].Field2) goto LA18_;
						x.len = 0; x.p = NIM_NIL;
						eqcopy___stdZassertions_16((&key_2), (*env__EZMLnBFjz0ylido4MSOE4A).data.p->data[h_2].Field0);
						eqcopy___stdZassertions_16((&val_2), (*env__EZMLnBFjz0ylido4MSOE4A).data.p->data[h_2].Field1);
						T20_.len = 0; T20_.p = NIM_NIL;
						T20_ = rawNewString(key_2.len + val_2.len + 1);
appendString((&T20_), key_2);
appendString((&T20_), TM__HZdw8BhppcTQo8DIK46LSg_20);
appendString((&T20_), val_2);
						x = T20_;
						copyMem__system_1719(((void*) ((&str[L]))), ((void*) (nimToCStringConv(x))), ((NI) ((NI)(x.len + ((NI)1)))));
						L += (NI)(x.len + ((NI)1));
						eqdestroy___stdZassertions_13((&x));
					}
					LA18_: ;
					res_2 += ((NI)1);
				} LA15: ;
			}
		}
		eqdestroy___stdZassertions_13((&val_2));
		eqdestroy___stdZassertions_13((&key_2));
	}
	result.Field0 = str;
	result.Field1 = L;
	return result;
}
static N_INLINE(void, fileClose__pureZosproc_643)(NI* h__5W9bedCO9agnTYBS7PJaxP4g) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(((NI)4) < (*h__5W9bedCO9agnTYBS7PJaxP4g))) goto LA3_;
		closeHandleCheck__pureZosproc_636((*h__5W9bedCO9agnTYBS7PJaxP4g));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*h__5W9bedCO9agnTYBS7PJaxP4g) = ((NI)-1);
	}
	LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, eqeq___system_7539)(NCSTRING x__Z3lojyrZeeORXB9aFmHlS7w, NCSTRING y__SlnicWIZiUaUC9cl2PfooTA) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		if (!(((void*) (x__Z3lojyrZeeORXB9aFmHlS7w)) == ((void*) (y__SlnicWIZiUaUC9cl2PfooTA)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		T6_ = (NIM_BOOL)0;
		T6_ = (x__Z3lojyrZeeORXB9aFmHlS7w == 0);
		if (T6_) goto LA7_;
		T6_ = (y__SlnicWIZiUaUC9cl2PfooTA == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		T11_ = (int)0;
		T11_ = strcmp(x__Z3lojyrZeeORXB9aFmHlS7w, y__SlnicWIZiUaUC9cl2PfooTA);
		result = (T11_ == ((NI32)0));
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, fileClose__pureZosproc_929)(int* h__5W9bedCO9agnTYBS7PJaxP4g_2) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(((NI32)4) < (*h__5W9bedCO9agnTYBS7PJaxP4g_2))) goto LA3_;
		closeHandleCheck__pureZosproc_636(((NI) ((*h__5W9bedCO9agnTYBS7PJaxP4g_2))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*h__5W9bedCO9agnTYBS7PJaxP4g_2) = ((int)-1);
	}
	LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, closeThreadAndProcessHandle__pureZosproc_917)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__i0Khfx3LaRvZjWf5mMrbng) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!(((*p__i0Khfx3LaRvZjWf5mMrbng).fThreadHandle == ((NI)0)))) goto LA3_;
		closeHandleCheck__pureZosproc_636((*p__i0Khfx3LaRvZjWf5mMrbng).fThreadHandle);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*p__i0Khfx3LaRvZjWf5mMrbng).fThreadHandle = ((NI)0);
	}
	LA3_: ;
	{
		if (!!(((*p__i0Khfx3LaRvZjWf5mMrbng).fProcessHandle == ((NI)0)))) goto LA7_;
		closeHandleCheck__pureZosproc_636((*p__i0Khfx3LaRvZjWf5mMrbng).fProcessHandle);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*p__i0Khfx3LaRvZjWf5mMrbng).fProcessHandle = ((NI)0);
	}
	LA7_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nospclose)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__WsqIZlX7CGSPiON9am13V9aw) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!!((((*p__WsqIZlX7CGSPiON9am13V9aw).options &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)4)))&7U)))!=0))) goto LA3_;
		{
			if (!((*p__WsqIZlX7CGSPiON9am13V9aw).inStream == ((tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*) NIM_NIL))) goto LA7_;
			fileClose__pureZosproc_929((&(*p__WsqIZlX7CGSPiON9am13V9aw).inHandle));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA5_;
		LA7_: ;
		{
			close__pureZstreams_58((*p__WsqIZlX7CGSPiON9am13V9aw).inStream);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA5_: ;
		{
			if (!!(((*p__WsqIZlX7CGSPiON9am13V9aw).outHandle == (*p__WsqIZlX7CGSPiON9am13V9aw).errHandle))) goto LA12_;
			fileClose__pureZosproc_929((&(*p__WsqIZlX7CGSPiON9am13V9aw).errHandle));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA12_: ;
		fileClose__pureZosproc_929((&(*p__WsqIZlX7CGSPiON9am13V9aw).outHandle));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	closeThreadAndProcessHandle__pureZosproc_917(p__WsqIZlX7CGSPiON9am13V9aw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg*, nospstartProcess)(NimStringV2 command__td0V6TIK9bkKmaFJWeVBaVA, NimStringV2 workingDir__5SDamHy49cOhPaAsmtOC63A, NimStringV2* args__OqKG9b6auqqw28FSytKfUWA, NI args__OqKG9b6auqqw28FSytKfUWALen_0, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* env__sV8uELyKNv4uoi3EYenWzg, tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options__gEn0pKixzTB9a2na0EDA0vQ) {
	tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* result;
	NimStringV2 cmdRoot;
	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A tmp;
	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A ee;
	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A wwd;
	tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ si;
	tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg procInfo;
	NI success;
	NI hi;
	NI ho;
	NI he;
	NCSTRING cmdl;
	NCSTRING wd;
	tyTuple__0hEbbYmlam6yzyW5MFo9cjg e;
	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A T56_;
	NI32 flags;
	NI16* T66_;
	NI16* T67_;
	NI16* T68_;
	NI32 T69_;
	NI32 lastError;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	cmdRoot.len = 0; cmdRoot.p = NIM_NIL;
	nimZeroMem((void*)(&tmp), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
	nimZeroMem((void*)(&ee), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
	nimZeroMem((void*)(&wwd), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
	nimZeroMem((void*)(&si), sizeof(tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ));
	nimZeroMem((void*)(&procInfo), sizeof(tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg));
	success = (NI)0;
	hi = (NI)0;
	ho = (NI)0;
	he = (NI)0;
	eqdestroy___pureZosproc_206(&result);
	result = (tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg*) nimNewObj(sizeof(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg), NIM_ALIGNOF(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg));
	(*result).Sup.m_type = (&NTIv2__2rGNQnv9bU4hanI2g3svReg_);
	(*result).options = options__gEn0pKixzTB9a2na0EDA0vQ;
	(*result).exitFlag = NIM_TRUE;
	si.cb = ((int)68);
	{
		if (!!(((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)4)))&7U)))!=0))) goto LA4_;
		si.dwFlags = ((NI32)256);
		{
			if (!!(((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)5)))&7U)))!=0))) goto LA8_;
			createPipeHandles__pureZosproc_787((&si.hStdInput), (&hi));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			createPipeHandles__pureZosproc_787((&ho), (&si.hStdOutput));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				if (!((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)3)))&7U)))!=0)) goto LA12_;
				si.hStdError = si.hStdOutput;
				he = ho;
			}
			goto LA10_;
			LA12_: ;
			{
				createPipeHandles__pureZosproc_787((&he), (&si.hStdError));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				{
					NI32 T17_;
					NI32 T20_;
					T17_ = (NI32)0;
					T17_ = Dl_1442841175_(he, ((NI32)1), ((NI32)0));
					if (!(T17_ == ((NI32)0))) goto LA18_;
					T20_ = (NI32)0;
					T20_ = osLastError__stdZoserrors_89();
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					raiseOSError__stdZoserrors_86(T20_, TM__HZdw8BhppcTQo8DIK46LSg_5);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA18_: ;
			}
			LA10_: ;
			{
				NI32 T23_;
				NI32 T26_;
				T23_ = (NI32)0;
				T23_ = Dl_1442841175_(hi, ((NI32)1), ((NI32)0));
				if (!(T23_ == ((NI32)0))) goto LA24_;
				T26_ = (NI32)0;
				T26_ = osLastError__stdZoserrors_89();
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				raiseOSError__stdZoserrors_86(T26_, TM__HZdw8BhppcTQo8DIK46LSg_6);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
			LA24_: ;
			{
				NI32 T29_;
				NI32 T32_;
				T29_ = (NI32)0;
				T29_ = Dl_1442841175_(ho, ((NI32)1), ((NI32)0));
				if (!(T29_ == ((NI32)0))) goto LA30_;
				T32_ = (NI32)0;
				T32_ = osLastError__stdZoserrors_89();
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				raiseOSError__stdZoserrors_86(T32_, TM__HZdw8BhppcTQo8DIK46LSg_7);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
			LA30_: ;
		}
		goto LA6_;
		LA8_: ;
		{
			createAllPipeHandles__pureZosproc_752((&si), (&hi), (&ho), (&he), ((NI) (result)));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA6_: ;
		(*result).inHandle = ((int) (hi));
		(*result).outHandle = ((int) (ho));
		(*result).errHandle = ((int) (he));
	}
	goto LA2_;
	LA4_: ;
	{
		si.hStdError = Dl_1442840741_(((NI32)-12));
		si.hStdInput = Dl_1442840741_(((NI32)-10));
		si.hStdOutput = Dl_1442840741_(((NI32)-11));
		(*result).inHandle = ((int) (si.hStdInput));
		(*result).outHandle = ((int) (si.hStdOutput));
		(*result).errHandle = ((int) (si.hStdError));
	}
	LA2_: ;
	cmdl = (NCSTRING)0;
	{
		if (!((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)2)))&7U)))!=0)) goto LA37_;
		cmdl = nimToCStringConv(command__td0V6TIK9bkKmaFJWeVBaVA);
	}
	goto LA35_;
	LA37_: ;
	{
		cmdRoot = buildCommandLine__pureZosproc_701(command__td0V6TIK9bkKmaFJWeVBaVA, args__OqKG9b6auqqw28FSytKfUWA, args__OqKG9b6auqqw28FSytKfUWALen_0);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		cmdl = nimToCStringConv(cmdRoot);
	}
	LA35_: ;
	wd = ((NCSTRING) NIM_NIL);
	e = TM__HZdw8BhppcTQo8DIK46LSg_18;
	{
		if (!(((NI)0) < workingDir__5SDamHy49cOhPaAsmtOC63A.len)) goto LA42_;
		wd = nimToCStringConv(workingDir__5SDamHy49cOhPaAsmtOC63A);
	}
	LA42_: ;
	{
		if (!!((env__sV8uELyKNv4uoi3EYenWzg == ((tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*) NIM_NIL)))) goto LA46_;
		e = buildEnv__pureZosproc_713(env__sV8uELyKNv4uoi3EYenWzg);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA46_: ;
	{
		NimStringV2 colontmpD_;
		tyArray__nHXaesL0DJZHyVS07ARPRA T53_;
		if (!((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)0)))&7U)))!=0)) goto LA50_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD_ = cstrToNimstr(cmdl);
		T53_[0] = colontmpD_;
		echoBinSafe(T53_, 1);
		{
			LA52_:;
		}
		{
			eqdestroy___stdZassertions_13((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA50_: ;
	tmp = newWideCString__stdZwidestrs_281(cmdl);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!(e.Field0 == 0)) goto LA59_;
		ee = newWideCString__stdZwidestrs_281(((NCSTRING) NIM_NIL));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA57_;
	LA59_: ;
	{
		ee = newWideCString__stdZwidestrs_260(e.Field0, e.Field1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA57_: ;
	wwd = newWideCString__stdZwidestrs_281(wd);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	flags = ((NI32)1056);
	{
		if (!((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)6)))&7U)))!=0)) goto LA64_;
		flags = (NI32)(flags | ((NI32)134217728));
	}
	LA64_: ;
	T66_ = (NI16*)0;
	T66_ = toWideCString__stdZwidestrs_41(tmp);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T67_ = (NI16*)0;
	T67_ = toWideCString__stdZwidestrs_41(ee);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T68_ = (NI16*)0;
	T68_ = toWideCString__stdZwidestrs_41(wwd);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T69_ = (NI32)0;
	T69_ = Dl_1442840717_(((NI16*) NIM_NIL), T66_, ((tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw*) NIM_NIL), ((tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw*) NIM_NIL), ((NI32)1), flags, T67_, T68_, (&si), (&procInfo));
	success = ((NI) (T69_));
	lastError = osLastError__stdZoserrors_89();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!!(((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)4)))&7U)))!=0))) goto LA72_;
		fileClose__pureZosproc_643((&si.hStdInput));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		fileClose__pureZosproc_643((&si.hStdOutput));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		{
			if (!!(((options__gEn0pKixzTB9a2na0EDA0vQ &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)3)))&7U)))!=0))) goto LA76_;
			fileClose__pureZosproc_643((&si.hStdError));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA76_: ;
	}
	LA72_: ;
	{
		NIM_BOOL T80_;
		T80_ = (NIM_BOOL)0;
		T80_ = eqeq___system_7539(e.Field0, ((NCSTRING) NIM_NIL));
		if (!!(T80_)) goto LA81_;
		dealloc(((void*) (e.Field0)));
	}
	LA81_: ;
	{
		if (!(success == ((NI)0))) goto LA85_;
		{
			if (!(((*result).options &((NU8)1<<((NU)((((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA)5)))&7U)))!=0)) goto LA89_;
			nospclose(result);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA89_: ;
		{
			NimStringV2 colontmpD__2;
			NimStringV2 colontmpD__3;
			if (!(((NI) (lastError)) == ((NI)87) || ((NI) (lastError)) == ((NI)2))) goto LA93_;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			eqcopy___stdZassertions_16((&colontmpD__2), command__td0V6TIK9bkKmaFJWeVBaVA);
			colontmpD__3 = nsuFormatSingleElem(TM__HZdw8BhppcTQo8DIK46LSg_22, colontmpD__2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA95_;
			raiseOSError__stdZoserrors_86(lastError, colontmpD__3);
			if (NIM_UNLIKELY(*nimErr_)) goto LA95_;
			{
				LA95_:;
			}
			{
				eqdestroy___stdZassertions_13((&colontmpD__3));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA91_;
		LA93_: ;
		{
			raiseOSError__stdZoserrors_86(lastError, command__td0V6TIK9bkKmaFJWeVBaVA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA91_: ;
	}
	LA85_: ;
	(*result).fProcessHandle = procInfo.hProcess;
	(*result).fThreadHandle = procInfo.hThread;
	(*result).id = ((NI) (procInfo.dwProcessId));
	(*result).exitFlag = NIM_FALSE;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_6((&wwd));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___stdZwidestrs_6((&ee));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___stdZwidestrs_6((&tmp));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___stdZassertions_13((&cmdRoot));
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_646)(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ** dest__wO8y9aLM5jbMyT4Eh0U2FHw_3) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_3));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__wO8y9aLM5jbMyT4Eh0U2FHw_3));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, hsClose__pureZosproc_641)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__jwdr0iZTC7EhOUl1b6sKUA) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	fileClose__pureZosproc_643((&(*((tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ*) (s__jwdr0iZTC7EhOUl1b6sKUA))).handle));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hsAtEnd__pureZosproc_677)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__Q9abPn9bfJx9cdeCyy7jzNtjg) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	result = (*((tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ*) (s__Q9abPn9bfJx9cdeCyy7jzNtjg))).atTheEnd;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, hsReadData__pureZosproc_680)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__LkmFLRyQRfFgkFiRuysVAw, void* buffer__02lNwaDQknHCXR2VdqOD4w, NI bufLen__b0n9bSUu1R9aCv7tugzsabMg) {
	NI result;
	tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ* s_2;
	NI32 br;
	NI32 a;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	s_2 = NIM_NIL;
	s_2 = ((tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ*) (s__LkmFLRyQRfFgkFiRuysVAw));
	{
		if (!(*s_2).atTheEnd) goto LA3_;
		result = ((NI)0);
		goto BeforeRet_;
	}
	LA3_: ;
	br = (NI32)0;
	a = Dl_1442840684_((*s_2).handle, buffer__02lNwaDQknHCXR2VdqOD4w, ((int) (bufLen__b0n9bSUu1R9aCv7tugzsabMg)), (&br), NIM_NIL);
	{
		NIM_BOOL T7_;
		NI32 T11_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI32)0));
		if (!(T7_)) goto LA8_;
		T7_ = !((br == ((NI32)0)));
		LA8_: ;
		if (!T7_) goto LA9_;
		T11_ = (NI32)0;
		T11_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_86(T11_, TM__HZdw8BhppcTQo8DIK46LSg_24);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA9_: ;
	(*s_2).atTheEnd = (br == ((NI32)0));
	result = ((NI) (br));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, hsWriteData__pureZosproc_688)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__Go9cytw9cKc4d29ctlEiZa8gQ, void* buffer__E8jpWqJ11Ij9atIWxGivFnA, NI bufLen__7hH1SdmRNKtBuKKYSCas9cQ) {
	tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ* s_2;
	NI32 bytesWritten;
	NI32 a;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s_2 = NIM_NIL;
	s_2 = ((tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ*) (s__Go9cytw9cKc4d29ctlEiZa8gQ));
	bytesWritten = (NI32)0;
	a = Dl_1442840690_((*s_2).handle, buffer__E8jpWqJ11Ij9atIWxGivFnA, ((int) (bufLen__7hH1SdmRNKtBuKKYSCas9cQ)), (&bytesWritten), NIM_NIL);
	{
		NI32 T5_;
		if (!(a == ((NI32)0))) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_86(T5_, TM__HZdw8BhppcTQo8DIK46LSg_25);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ*, newFileHandleStream__pureZosproc_695)(NI handle__oHkPLB9axgGQ9cxQu9biOR9aNw) {
	tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ* result;
	result = NIM_NIL;
	eqdestroy___pureZosproc_646(&result);
	result = (tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ*) nimNewObj(sizeof(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ), NIM_ALIGNOF(tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ));
	(*result).Sup.Sup.m_type = (&NTIv2__Uwf6VGZy4JPKquxCiOCalQ_);
	(*result).handle = handle__oHkPLB9axgGQ9cxQu9biOR9aNw;
	(*result).Sup.closeImpl = hsClose__pureZosproc_641;
	(*result).Sup.atEndImpl = hsAtEnd__pureZosproc_677;
	(*result).Sup.readDataImpl = hsReadData__pureZosproc_680;
	(*result).Sup.writeDataImpl = hsWriteData__pureZosproc_688;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*, nospinputStream)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__cewAKsIlXrf47EwbijyVdA) {
	tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ* T5_;
		if (!((*p__cewAKsIlXrf47EwbijyVdA).inStream == ((tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*) NIM_NIL))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = newFileHandleStream__pureZosproc_695(((NI) ((*p__cewAKsIlXrf47EwbijyVdA).inHandle)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqsink___pureZstreams_620(&(*p__cewAKsIlXrf47EwbijyVdA).inStream, &T5_->Sup);
	}
	LA3_: ;
	eqcopy___pureZstreams_616(&result, (*p__cewAKsIlXrf47EwbijyVdA).inStream, NIM_FALSE);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*, nospoutputStream)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__qaL4brv79ac69aLBwudCF4VQ) {
	tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		tyObject_FileHandleStreamcolonObjectType___Uwf6VGZy4JPKquxCiOCalQ* T5_;
		if (!((*p__qaL4brv79ac69aLBwudCF4VQ).outStream == ((tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ*) NIM_NIL))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = newFileHandleStream__pureZosproc_695(((NI) ((*p__qaL4brv79ac69aLBwudCF4VQ).outHandle)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqsink___pureZstreams_620(&(*p__qaL4brv79ac69aLBwudCF4VQ).outStream, &T5_->Sup);
	}
	LA3_: ;
	eqcopy___pureZstreams_616(&result, (*p__qaL4brv79ac69aLBwudCF4VQ).outStream, NIM_FALSE);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosprunning)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__EMbBqhuu9aDwmVfDAhHNsjw) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(*p__EMbBqhuu9aDwmVfDAhHNsjw).exitFlag) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		NI32 x;
		x = Dl_1442840732_((*p__EMbBqhuu9aDwmVfDAhHNsjw).fProcessHandle, ((NI32)0));
		result = (x == ((NI32)258));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nospterminate)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__PDEn8aci3oMM5ysYVh9asAQ) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		NI32 T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = nosprunning(p__PDEn8aci3oMM5ysYVh9asAQ);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		T6_ = (NI32)0;
		T6_ = Dl_1442840735_((*p__PDEn8aci3oMM5ysYVh9asAQ).fProcessHandle, ((NI)0));
		(void)(T6_);
	}
	LA4_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nospwaitForExit)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__hUK4B8yW50r9ar7GPvflLQA, NI timeout__DDDS0NJhst3CHPYe2zkz4Q) {
	NI result;
	NI32 res;
	NI32 status;
	NI32 T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!(*p__hUK4B8yW50r9ar7GPvflLQA).exitFlag) goto LA3_;
		result = ((NI) ((*p__hUK4B8yW50r9ar7GPvflLQA).exitStatus));
		goto BeforeRet_;
	}
	LA3_: ;
	res = Dl_1442840732_((*p__hUK4B8yW50r9ar7GPvflLQA).fProcessHandle, ((NI32) (timeout__DDDS0NJhst3CHPYe2zkz4Q)));
	{
		if (!(res == ((NI32)258))) goto LA7_;
		nospterminate(p__hUK4B8yW50r9ar7GPvflLQA);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA7_: ;
	status = (NI32)0;
	T9_ = (NI32)0;
	T9_ = Dl_1442840738_((*p__hUK4B8yW50r9ar7GPvflLQA).fProcessHandle, (&status));
	(void)(T9_);
	{
		if (!!((status == ((NI32)259)))) goto LA12_;
		(*p__hUK4B8yW50r9ar7GPvflLQA).exitFlag = NIM_TRUE;
		(*p__hUK4B8yW50r9ar7GPvflLQA).exitStatus = status;
		closeThreadAndProcessHandle__pureZosproc_917(p__hUK4B8yW50r9ar7GPvflLQA);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = ((NI) (status));
	}
	goto LA10_;
	LA12_: ;
	{
		result = ((NI)-1);
	}
	LA10_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_1482)(tyTuple__XOVT24GHXwqiEj5GCsEGCA* dest__qKc2jknF30aTLZ7Tc9cVb4A) {
	eqdestroy___stdZassertions_13((&(*dest__qKc2jknF30aTLZ7Tc9cVb4A).Field0));
}
N_LIB_PRIVATE N_NIMCALL(NI, nosppeekExitCode)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p__BdpVZkdOF4TjY3Vnu5hsOw) {
	NI result;
	NIM_BOOL b;
	NI32 T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!(*p__BdpVZkdOF4TjY3Vnu5hsOw).exitFlag) goto LA3_;
		result = ((NI) ((*p__BdpVZkdOF4TjY3Vnu5hsOw).exitStatus));
		goto BeforeRet_;
	}
	LA3_: ;
	result = ((NI)-1);
	T5_ = (NI32)0;
	T5_ = Dl_1442840732_((*p__BdpVZkdOF4TjY3Vnu5hsOw).fProcessHandle, ((NI32)0));
	b = (T5_ == ((NI32)258));
	{
		NI32 status;
		NI32 T10_;
		if (!!(b)) goto LA8_;
		status = (NI32)0;
		T10_ = (NI32)0;
		T10_ = Dl_1442840738_((*p__BdpVZkdOF4TjY3Vnu5hsOw).fProcessHandle, (&status));
		(void)(T10_);
		(*p__BdpVZkdOF4TjY3Vnu5hsOw).exitFlag = NIM_TRUE;
		(*p__BdpVZkdOF4TjY3Vnu5hsOw).exitStatus = status;
		closeThreadAndProcessHandle__pureZosproc_917(p__BdpVZkdOF4TjY3Vnu5hsOw);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = ((NI) (status));
	}
	LA8_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__XOVT24GHXwqiEj5GCsEGCA, execCmdEx__pureZosproc_1441)(NimStringV2 command__i6CyqWcCkFCyKxG83Tim6A, tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options__3BGR5KBCEy9bxfjpnWO51NQ, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* env__bgltpE1TqEueNAME9cMTobg, NimStringV2 workingDir__jx0Kfq9bjLXHaUognSs0wsg, NimStringV2 input__BZ0rGpyqEQIpxDrGZO9af5Q) {
	tyTuple__XOVT24GHXwqiEj5GCsEGCA result;
	tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p;
	tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* outp;
	tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* colontmpD_;
	NimStringV2 colontmp_;
	NimStringV2 line;
	tyArray__8ZvwQIddfpj2THRVPsFzIQ T2_;
	NI colontmp__2;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyTuple__XOVT24GHXwqiEj5GCsEGCA));
	p = NIM_NIL;
	outp = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmp_.len = 0; colontmp_.p = NIM_NIL;
	line.len = 0; line.p = NIM_NIL;
	p = nospstartProcess(command__i6CyqWcCkFCyKxG83Tim6A, workingDir__jx0Kfq9bjLXHaUognSs0wsg, T2_, 0, env__bgltpE1TqEueNAME9cMTobg, (options__3BGR5KBCEy9bxfjpnWO51NQ | 4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	outp = nospoutputStream(p);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* colontmpD__2;
		if (!(((NI)0) < input__BZ0rGpyqEQIpxDrGZO9af5Q.len)) goto LA5_;
		colontmpD__2 = NIM_NIL;
		colontmpD__2 = nospinputStream(p);
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		write__pureZstreams_184(colontmpD__2, input__BZ0rGpyqEQIpxDrGZO9af5Q);
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		{
			LA7_:;
		}
		{
			eqdestroy___pureZstreams_613(&colontmpD__2);
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA5_: ;
	colontmpD_ = nospinputStream(p);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	close__pureZstreams_58(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmp_ = TM__HZdw8BhppcTQo8DIK46LSg_26;
	colontmp__2 = ((NI)-1);
	blitTmp = colontmp_;
	colontmp_.len = 0; colontmp_.p = NIM_NIL;
	result.Field0 = blitTmp;
	result.Field1 = colontmp__2;
	line = rawNewString(((NI)120));
	{
		while (1) {
			{
				NIM_BOOL T14_;
				T14_ = (NIM_BOOL)0;
				T14_ = readLine__pureZstreams_543(outp, (&line));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				if (!T14_) goto LA15_;
				prepareAdd((&result.Field0), line.len + 0);
appendString((&result.Field0), line);
				prepareAdd((&result.Field0), 1);
appendString((&result.Field0), TM__HZdw8BhppcTQo8DIK46LSg_28);
			}
			goto LA12_;
			LA15_: ;
			{
				NI T18_;
				T18_ = (NI)0;
				T18_ = nosppeekExitCode(p);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				result.Field1 = T18_;
				{
					if (!!((result.Field1 == ((NI)-1)))) goto LA21_;
					goto LA10;
				}
				LA21_: ;
			}
			LA12_: ;
		}
	} LA10: ;
	nospclose(p);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___stdZassertions_13((&line));
		eqdestroy___stdZassertions_13((&colontmp_));
		eqdestroy___pureZstreams_613(&colontmpD_);
		eqdestroy___pureZstreams_613(&outp);
		eqdestroy___pureZosproc_206(&p);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nospexecCmd)(NimStringV2 command__YNo3gXnKY60raWUuVzsOLg) {
	NI result;
	tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A c;
	tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ si;
	tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg procInfo;
	NI process;
	NI32 L;
	NI32 res;
	NI16* T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimZeroMem((void*)(&c), sizeof(tyObject_WideCStringObj__BwbUsAz4qeNPsD7q6SJ32A));
	nimZeroMem((void*)(&si), sizeof(tyObject_STARTUPINFO__WGlpKvY9cdd69bAwMQMNLYoQ));
	nimZeroMem((void*)(&procInfo), sizeof(tyObject_PROCESS_INFORMATION__rpgAdaffN9b79bo2kEQiFsMg));
	process = (NI)0;
	L = (NI32)0;
	si.cb = ((int)68);
	si.hStdError = Dl_1442840741_(((NI32)-12));
	si.hStdInput = Dl_1442840741_(((NI32)-10));
	si.hStdOutput = Dl_1442840741_(((NI32)-11));
	c = newWideCString__stdZwidestrs_287(command__YNo3gXnKY60raWUuVzsOLg);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = (NI16*)0;
	T2_ = toWideCString__stdZwidestrs_41(c);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	res = Dl_1442840717_(((NI16*) NIM_NIL), T2_, ((tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw*) NIM_NIL), ((tyObject_SECURITY_ATTRIBUTES__P4HW9ceaevTBZ5O3kGC8yyw*) NIM_NIL), ((NI32)0), ((NI32)32), ((NI16*) NIM_NIL), ((NI16*) NIM_NIL), (&si), (&procInfo));
	{
		NI32 T7_;
		if (!(res == ((NI32)0))) goto LA5_;
		T7_ = (NI32)0;
		T7_ = osLastError__stdZoserrors_89();
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		raiseOSError__stdZoserrors_86(T7_, TM__HZdw8BhppcTQo8DIK46LSg_29);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	goto LA3_;
	LA5_: ;
	{
		NI32 T9_;
		NI32 T17_;
		process = procInfo.hProcess;
		T9_ = (NI32)0;
		T9_ = Dl_1442840682_(procInfo.hThread);
		(void)(T9_);
		{
			NI32 T12_;
			NI32 T15_;
			T12_ = (NI32)0;
			T12_ = Dl_1442840732_(process, ((NI32)-1));
			if (!!((T12_ == ((NI32)-1)))) goto LA13_;
			T15_ = (NI32)0;
			T15_ = Dl_1442840738_(process, (&L));
			(void)(T15_);
			result = ((NI) (L));
		}
		goto LA10_;
		LA13_: ;
		{
			result = ((NI)-1);
		}
		LA10_: ;
		T17_ = (NI32)0;
		T17_ = Dl_1442840682_(process);
		(void)(T17_);
	}
	LA3_: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___stdZwidestrs_6((&c));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZosproc_1488)(tyTuple__XOVT24GHXwqiEj5GCsEGCA* dest__6nAg1OGI9aYnL5Y9bUk8IxUg, tyTuple__XOVT24GHXwqiEj5GCsEGCA src__WNVcB9bWsF9cE7TspFl4X0Ig) {
	if ((*dest__6nAg1OGI9aYnL5Y9bUk8IxUg).Field0.p != src__WNVcB9bWsF9cE7TspFl4X0Ig.Field0.p) {	eqdestroy___stdZassertions_13((&(*dest__6nAg1OGI9aYnL5Y9bUk8IxUg).Field0));
	}
(*dest__6nAg1OGI9aYnL5Y9bUk8IxUg).Field0.len = src__WNVcB9bWsF9cE7TspFl4X0Ig.Field0.len; (*dest__6nAg1OGI9aYnL5Y9bUk8IxUg).Field0.p = src__WNVcB9bWsF9cE7TspFl4X0Ig.Field0.p;
	(*dest__6nAg1OGI9aYnL5Y9bUk8IxUg).Field1 = src__WNVcB9bWsF9cE7TspFl4X0Ig.Field1;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_559)(tyProc__SqRJqa5aOiKB4EuKlKh9asA* dest__szRsFbX2QY1GVJ1jt4RlPg) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest__szRsFbX2QY1GVJ1jt4RlPg).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__szRsFbX2QY1GVJ1jt4RlPg).ClE_0);
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nospcountProcessors)(void) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = ncpicountProcessors();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZosproc_213)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg** dest__aDT2vBnQ9bz4A0OSp9cSE9aNA, tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* src__UGcAo9cTo1ajuY9aMQsdbGqA) {
	tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* colontmp_;
	colontmp_ = (*dest__aDT2vBnQ9bz4A0OSp9cSE9aNA);
	(*dest__aDT2vBnQ9bz4A0OSp9cSE9aNA) = src__UGcAo9cTo1ajuY9aMQsdbGqA;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn(colontmp_);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(colontmp_);
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nospexecProcesses)(NimStringV2* cmds__S6ltKaqo1vd2rA0JYGTZ0Q, NI cmds__S6ltKaqo1vd2rA0JYGTZ0QLen_0, tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options__SOxRkpbUm0l9cOVKhpddsEw, NI n__ATvbkl0dkIlSz63SoLq9b6A, tyProc__SqRJqa5aOiKB4EuKlKh9asA beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA, tyProc__oudJckli4GdxAXLVzBBlAw afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		tySequence__PrBYolTs4TOSgE8v5oqDUQ q;
		tySequence__qwqHTkRvwhrRyENtudHQ7g idxs;
		NI i;
		tyArray__SLBTEB08vk46ttuRaTxAYw w;
		NI m;
		NI wcount;
		NI ecount;
		if (!(((NI)1) < n__ATvbkl0dkIlSz63SoLq9b6A)) goto LA3_;
		q.len = 0; q.p = NIM_NIL;
		idxs.len = 0; idxs.p = NIM_NIL;
		i = ((NI)0);
		q = newSeq__pureZosproc_267(((NI) (n__ATvbkl0dkIlSz63SoLq9b6A)));
		idxs = newSeq__pureZosproc_398(((NI) (n__ATvbkl0dkIlSz63SoLq9b6A)));
		nimZeroMem((void*)w, sizeof(tyArray__SLBTEB08vk46ttuRaTxAYw));
		m = ((((n__ATvbkl0dkIlSz63SoLq9b6A <= ((NI)64)) ? n__ATvbkl0dkIlSz63SoLq9b6A : ((NI)64)) <= cmds__S6ltKaqo1vd2rA0JYGTZ0QLen_0) ? ((n__ATvbkl0dkIlSz63SoLq9b6A <= ((NI)64)) ? n__ATvbkl0dkIlSz63SoLq9b6A : ((NI)64)) : cmds__S6ltKaqo1vd2rA0JYGTZ0QLen_0);
		wcount = m;
		{
			while (1) {
				tyArray__8ZvwQIddfpj2THRVPsFzIQ T12_;
				tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* T13_;
				if (!(i < m)) goto LA7				;
				{
					if (!!((beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0 == TM__HZdw8BhppcTQo8DIK46LSg_30.ClP_0 && beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0 == TM__HZdw8BhppcTQo8DIK46LSg_30.ClE_0))) goto LA10_;
					beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0? beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0(i, beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0):((TM__HZdw8BhppcTQo8DIK46LSg_31)(beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0))(i);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				}
				LA10_: ;
				T13_ = NIM_NIL;
				T13_ = nospstartProcess(cmds__S6ltKaqo1vd2rA0JYGTZ0Q[i], TM__HZdw8BhppcTQo8DIK46LSg_32, T12_, 0, ((tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*) NIM_NIL), (options__SOxRkpbUm0l9cOVKhpddsEw | 4));
				if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				eqsink___pureZosproc_213(&q.p->data[i], T13_);
				idxs.p->data[i] = i;
				w[(i)- 0] = (*q.p->data[i]).fProcessHandle;
				i += ((NI)1);
			} LA7: ;
		}
		ecount = cmds__S6ltKaqo1vd2rA0JYGTZ0QLen_0;
		{
			while (1) {
				NI rexit;
				NI32 ret;
				if (!(((NI)0) < ecount)) goto LA15				;
				rexit = ((NI)-1);
				ret = Dl_1442841126_(((NI32) (wcount)), w, ((NI32)0), ((NI32)-1));
				{
					if (!(ret == ((NI32)258))) goto LA18_;
				}
				goto LA16_;
				LA18_: ;
				{
					NI32 T23_;
					if (!(ret == ((NI32)-1))) goto LA21_;
					T23_ = (NI32)0;
					T23_ = osLastError__stdZoserrors_89();
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					raiseOSError__stdZoserrors_86(T23_, TM__HZdw8BhppcTQo8DIK46LSg_33);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
				}
				goto LA16_;
				LA21_: ;
				{
					NI32 status;
					status = (NI32)0;
					{
						NI r;
						NI colontmp_;
						NI res;
						r = (NI)0;
						colontmp_ = (NI)0;
						colontmp_ = (NI)(m - ((NI)1));
						res = ((NI)0);
						{
							while (1) {
								if (!(res <= colontmp_)) goto LA27								;
								r = res;
								{
									NIM_BOOL T30_;
									NI32 T34_;
									T30_ = (NIM_BOOL)0;
									T30_ = !((q.p->data[r] == 0));
									if (!(T30_)) goto LA31_;
									T30_ = ((*q.p->data[r]).fProcessHandle == w[(ret)- 0]);
									LA31_: ;
									if (!T30_) goto LA32_;
									T34_ = (NI32)0;
									T34_ = Dl_1442840738_((*q.p->data[r]).fProcessHandle, (&status));
									(void)(T34_);
									(*q.p->data[r]).exitFlag = NIM_TRUE;
									(*q.p->data[r]).exitStatus = status;
									rexit = r;
									goto LA25;
								}
								LA32_: ;
								res += ((NI)1);
							} LA27: ;
						}
					} LA25: ;
				}
				LA16_: ;
				{
					NI processHandle;
					NI T39_;
					if (!(((NI)0) <= rexit)) goto LA37_;
					processHandle = (*q.p->data[rexit]).fProcessHandle;
					T39_ = (NI)0;
					T39_ = nosppeekExitCode(q.p->data[rexit]);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					result = ((result >= (T39_ > 0? (T39_) : -(T39_))) ? result : (T39_ > 0? (T39_) : -(T39_)));
					{
						if (!!((afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClP_0 == TM__HZdw8BhppcTQo8DIK46LSg_34.ClP_0 && afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClE_0 == TM__HZdw8BhppcTQo8DIK46LSg_34.ClE_0))) goto LA42_;
						afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClE_0? afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClP_0(idxs.p->data[rexit], q.p->data[rexit], afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClE_0):((TM__HZdw8BhppcTQo8DIK46LSg_35)(afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClP_0))(idxs.p->data[rexit], q.p->data[rexit]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					}
					LA42_: ;
					nospclose(q.p->data[rexit]);
					if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
					{
						tyArray__8ZvwQIddfpj2THRVPsFzIQ T52_;
						tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* T53_;
						if (!(i < cmds__S6ltKaqo1vd2rA0JYGTZ0QLen_0)) goto LA46_;
						{
							if (!!((beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0 == TM__HZdw8BhppcTQo8DIK46LSg_30.ClP_0 && beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0 == TM__HZdw8BhppcTQo8DIK46LSg_30.ClE_0))) goto LA50_;
							beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0? beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0(i, beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0):((TM__HZdw8BhppcTQo8DIK46LSg_36)(beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0))(i);
							if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
						}
						LA50_: ;
						T53_ = NIM_NIL;
						T53_ = nospstartProcess(cmds__S6ltKaqo1vd2rA0JYGTZ0Q[i], TM__HZdw8BhppcTQo8DIK46LSg_37, T52_, 0, ((tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*) NIM_NIL), (options__SOxRkpbUm0l9cOVKhpddsEw | 4));
						if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
						eqsink___pureZosproc_213(&q.p->data[rexit], T53_);
						idxs.p->data[rexit] = i;
						w[(rexit)- 0] = (*q.p->data[rexit]).fProcessHandle;
						i += ((NI)1);
					}
					goto LA44_;
					LA46_: ;
					{
						{
							NI k;
							NI colontmp__2;
							NI res_2;
							k = (NI)0;
							colontmp__2 = (NI)0;
							colontmp__2 = (NI)(wcount - ((NI)1));
							res_2 = ((NI)0);
							{
								while (1) {
									if (!(res_2 <= colontmp__2)) goto LA57									;
									k = res_2;
									{
										if (!(w[(k)- 0] == processHandle)) goto LA60_;
										w[(k)- 0] = w[((NI)(wcount - ((NI)1)))- 0];
										w[((NI)(wcount - ((NI)1)))- 0] = ((NI)0);
										wcount -= ((NI)1);
										goto LA55;
									}
									LA60_: ;
									res_2 += ((NI)1);
								} LA57: ;
							}
						} LA55: ;
						eqsink___pureZosproc_213(&q.p->data[rexit], ((tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg*) NIM_NIL));
					}
					LA44_: ;
					ecount -= ((NI)1);
				}
				LA37_: ;
			} LA15: ;
		}
		{
			LA5_:;
		}
		{
			eqdestroy___pureZosproc_406((&idxs));
			eqdestroy___pureZosproc_275((&q));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI i_2;
			NI colontmp__3;
			NI res_3;
			i_2 = (NI)0;
			colontmp__3 = (NI)0;
			colontmp__3 = (cmds__S6ltKaqo1vd2rA0JYGTZ0QLen_0-1);
			res_3 = ((NI)0);
			{
				while (1) {
					tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* p;
					tyArray__8ZvwQIddfpj2THRVPsFzIQ T73_;
					NI T74_;
					if (!(res_3 <= colontmp__3)) goto LA67					;
					p = NIM_NIL;
					i_2 = res_3;
					{
						if (!!((beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0 == TM__HZdw8BhppcTQo8DIK46LSg_30.ClP_0 && beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0 == TM__HZdw8BhppcTQo8DIK46LSg_30.ClE_0))) goto LA71_;
						beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0? beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0(i_2, beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClE_0):((TM__HZdw8BhppcTQo8DIK46LSg_38)(beforeRunEvent__g6C5WJ9bN335HjOdqloMTMA.ClP_0))(i_2);
						if (NIM_UNLIKELY(*nimErr_)) goto LA68_;
					}
					LA71_: ;
					p = nospstartProcess(cmds__S6ltKaqo1vd2rA0JYGTZ0Q[i_2], TM__HZdw8BhppcTQo8DIK46LSg_39, T73_, 0, ((tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*) NIM_NIL), (options__SOxRkpbUm0l9cOVKhpddsEw | 4));
					if (NIM_UNLIKELY(*nimErr_)) goto LA68_;
					T74_ = (NI)0;
					T74_ = nospwaitForExit(p, ((NI)-1));
					if (NIM_UNLIKELY(*nimErr_)) goto LA68_;
					result = (((T74_ > 0? (T74_) : -(T74_)) >= result) ? (T74_ > 0? (T74_) : -(T74_)) : result);
					{
						if (!!((afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClP_0 == TM__HZdw8BhppcTQo8DIK46LSg_34.ClP_0 && afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClE_0 == TM__HZdw8BhppcTQo8DIK46LSg_34.ClE_0))) goto LA77_;
						afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClE_0? afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClP_0(i_2, p, afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClE_0):((TM__HZdw8BhppcTQo8DIK46LSg_40)(afterRunEvent__ZkNDEQKQeXNayzyqe9caYmw.ClP_0))(i_2, p);
						if (NIM_UNLIKELY(*nimErr_)) goto LA68_;
					}
					LA77_: ;
					nospclose(p);
					if (NIM_UNLIKELY(*nimErr_)) goto LA68_;
					res_3 += ((NI)1);
					{
						LA68_:;
					}
					{
						eqdestroy___pureZosproc_206(&p);
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				} LA67: ;
			}
		}
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_579)(tyProc__oudJckli4GdxAXLVzBBlAw* dest__szRsFbX2QY1GVJ1jt4RlPg_2) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest__szRsFbX2QY1GVJ1jt4RlPg_2).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest__szRsFbX2QY1GVJ1jt4RlPg_2).ClE_0);
	}
	LA4_: ;
}
