/* Generated by Nim Compiler v1.9.1 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q;
typedef struct tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA;
typedef struct tyObject_ConfigRefcolonObjectType___2BjaRtGfBjUbX51p9a4g9a9cg tyObject_ConfigRefcolonObjectType___2BjaRtGfBjUbX51p9a4g9a9cg;
typedef struct tyObject_TIdObj__jPSvrmNCWI4CL3MSWxUHJQ tyObject_TIdObj__jPSvrmNCWI4CL3MSWxUHJQ;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_ItemId__RG5oiYa2xm9bBBKInuP3ECw tyObject_ItemId__RG5oiYa2xm9bBBKInuP3ECw;
typedef struct tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ;
typedef struct tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ_Content tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ_Content;
typedef struct tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA;
typedef struct tyObject_TLoc__cQfx3WjJDtozqFtY4RdR9cA tyObject_TLoc__cQfx3WjJDtozqFtY4RdR9cA;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg;
typedef struct tyObject_TIdent__L29bfCasnfXpB7u88iPkwMA tyObject_TIdent__L29bfCasnfXpB7u88iPkwMA;
typedef struct tySequence__xxu3GgaFAGO6lOns9aHaeLQ tySequence__xxu3GgaFAGO6lOns9aHaeLQ;
typedef struct tySequence__xxu3GgaFAGO6lOns9aHaeLQ_Content tySequence__xxu3GgaFAGO6lOns9aHaeLQ_Content;
typedef struct tyObject_TLib__tP0u9cd1FuZgfCfM3WIm9cRg tyObject_TLib__tP0u9cd1FuZgfCfM3WIm9cRg;
typedef struct tyTuple__kN8up2W6YKc5YA9avn5mV5w tyTuple__kN8up2W6YKc5YA9avn5mV5w;
struct TNimTypeV2 {
void* destructor;
NI size;
NI16 align;
NI16 depth;
NU32* display;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tyObject_ItemId__RG5oiYa2xm9bBBKInuP3ECw {
NI32 module;
NI32 item;
};
struct tyObject_TIdObj__jPSvrmNCWI4CL3MSWxUHJQ {
  RootObj Sup;
tyObject_ItemId__RG5oiYa2xm9bBBKInuP3ECw itemId;
};
typedef NU8 tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ;
typedef NU8 tyEnum_TCallingConvention__XL1p2EKvOAlAHpc68ecZPw;
typedef NU64 tySet_tyEnum_TTypeFlag__wRa4s6r4s9cXJ9abWKsrci1Q;
struct tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ {
  NI len; tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ_Content* p;
};
typedef NU8 tyEnum_TLocKind__iCEcZjTaghPmL3Wx2e5DQw;
typedef NU8 tyEnum_TStorageLoc__BKvMXWvKko6Yn5329c9aw9afg;
typedef NU16 tySet_tyEnum_TLocFlag__9a7m8BSAfzn6yluCKaq6viw;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_TLoc__cQfx3WjJDtozqFtY4RdR9cA {
tyEnum_TLocKind__iCEcZjTaghPmL3Wx2e5DQw k;
tyEnum_TStorageLoc__BKvMXWvKko6Yn5329c9aw9afg storage;
tySet_tyEnum_TLocFlag__9a7m8BSAfzn6yluCKaq6viw flags;
tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* lode;
NimStringV2 r;
};
struct tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA {
  tyObject_TIdObj__jPSvrmNCWI4CL3MSWxUHJQ Sup;
tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ kind;
tyEnum_TCallingConvention__XL1p2EKvOAlAHpc68ecZPw callConv;
tySet_tyEnum_TTypeFlag__wRa4s6r4s9cXJ9abWKsrci1Q flags;
tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ sons;
tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n;
tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* owner;
tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* sym;
NI64 size;
NI16 align;
NI16 paddingAtEnd;
tyObject_TLoc__cQfx3WjJDtozqFtY4RdR9cA loc;
tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* typeInst;
tyObject_ItemId__RG5oiYa2xm9bBBKInuP3ECw uniqueId;
};
typedef NU8 tySet_tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ[9];
struct tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg {
NU16 line;
NI16 col;
NI32 fileIndex;
};
typedef NU32 tySet_tyEnum_TNodeFlag__69c8WThOUT3nlaj2cOZ9c2dw;
typedef NU8 tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ;
struct tySequence__xxu3GgaFAGO6lOns9aHaeLQ {
  NI len; tySequence__xxu3GgaFAGO6lOns9aHaeLQ_Content* p;
};
struct tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q {
tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* typ;
tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg info;
tySet_tyEnum_TNodeFlag__69c8WThOUT3nlaj2cOZ9c2dw flags;
tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ kind;
union{
struct {NI64 intVal;
} _kind_1;
struct {NF floatVal;
} _kind_2;
struct {NimStringV2 strVal;
} _kind_3;
struct {tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* sym;
} _kind_4;
struct {tyObject_TIdent__L29bfCasnfXpB7u88iPkwMA* ident;
} _kind_5;
struct {tySequence__xxu3GgaFAGO6lOns9aHaeLQ sons;
} _kind_6;
};
};
typedef NU8 tyEnum_TSymKind__EmlFK9c4sdJy7UDy5lm8yQQ;
typedef NU16 tyEnum_TMagic__mTDI9bmjHUNrwgx3GHm4Krg;
typedef NU64 tySet_tyEnum_TSymFlag__TAs9cOBd13PVhEf42OX9cOdg;
typedef NU32 tySet_tyEnum_TOption__PrH9cMsvu5oCG0HODAZ3CAg;
struct tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA {
  tyObject_TIdObj__jPSvrmNCWI4CL3MSWxUHJQ Sup;
tyEnum_TSymKind__EmlFK9c4sdJy7UDy5lm8yQQ kind;
union{
struct {tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* gcUnsafetyReason;
tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* transformedBody;
} _kind_1;
struct {tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* guard;
NI bitsize;
NI alignment;
} _kind_2;
};
tyEnum_TMagic__mTDI9bmjHUNrwgx3GHm4Krg magic;
tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* typ;
tyObject_TIdent__L29bfCasnfXpB7u88iPkwMA* name;
tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg info;
tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* owner;
tySet_tyEnum_TSymFlag__TAs9cOBd13PVhEf42OX9cOdg flags;
tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* ast;
tySet_tyEnum_TOption__PrH9cMsvu5oCG0HODAZ3CAg options;
NI position;
NI offset;
tyObject_TLoc__cQfx3WjJDtozqFtY4RdR9cA loc;
tyObject_TLib__tP0u9cd1FuZgfCfM3WIm9cRg* annex;
tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* constraint;
};
typedef NU8 tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA;
typedef NU8 tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw;
struct tyTuple__kN8up2W6YKc5YA9avn5mV5w {
NimStringV2 Field0;
NI Field1;
NI Field2;
};


#ifndef tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ_Content_PP
#define tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ_Content_PP
struct tySequence__iPgAQ0li6vRlH9cX9aT6CQgQ_Content { NI cap; tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__xxu3GgaFAGO6lOns9aHaeLQ_Content_PP
#define tySequence__xxu3GgaFAGO6lOns9aHaeLQ_Content_PP
struct tySequence__xxu3GgaFAGO6lOns9aHaeLQ_Content { NI cap; tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA*, skipTypes__ast_4803)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* t__59aRx2ozcYc9bLAC4O56qylA, tySet_tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ kinds__HMn6kCCg7XuHs39byTwMlvQ);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_3546)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA** dest__xUGZnk6LgW9ckUtke9chKW3g, tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* src__vkZbm6WIEuiiRIu4TGi3lg);
static N_INLINE(NI, len__ast_3325)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__XTPkz1jrUDzaDAHPseflHQ);
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*, ithField__semmacrosanity_54)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* t__oDmrDxr0nf8ja80Q9aQnFsQ, NI* field__tsAB9bChXl34vu09cEjrc2vQ);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___ast_4066)(tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA** dest__VQAzjFA4pS6k3b9cU6LNuQw, tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* src__UYvSVFOZNg2i8gJQynIEBg);
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*, ithField__semmacrosanity_5)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__yXlfnFjgNaWS51AFbh8yGQ, NI* field__tsAB9bChXl34vu09cEjrc2vQ_2);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q*, lastSon__ast_6268)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__gpwzfpTVVRehSuSfiPxoLQ_2);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_3454)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q** dest__grSiItv7LycMhpeWUvBn0A);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_4063)(tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA** dest__xUGZnk6LgW9ckUtke9chKW3g, tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* src__vkZbm6WIEuiiRIu4TGi3lg);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_3543)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA** dest__grSiItv7LycMhpeWUvBn0A);
N_LIB_PRIVATE N_NOINLINE(void, liMessage__msgs_1169)(tyObject_ConfigRefcolonObjectType___2BjaRtGfBjUbX51p9a4g9a9cg* conf__YKJQaQvv0hyWWGIJPWWxCg, tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg info__ocsVBTLmEoRQLLAuXfquhA, tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA msg__JwpAqN3XbRDCsr6o0M0row, NimStringV2 arg__zW9cECejKQ9b7gInjXO59a9c5Q, tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw eh__5N2vmYHL6tqamW6539aRS9cQ, tyTuple__kN8up2W6YKc5YA9avn5mV5w info2__YfwyQKDJcLAkRa9az9bNuiDA, NIM_BOOL isRaw__zpF2w4EIxTh71u9a4PuFizg);
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g);
static N_INLINE(void, copyMem__system_1719)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_3)(NI x__KsYCTjO9co8rDpst8JJ2TVg);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space__9cQ1OhOryhnk7At3WzUsjtA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_13)(NimStringV2* dest__C2JKGPCNdWKCPrsQvNywTQ);
static N_INLINE(NimStringV2, toFileLineCol__msgs_664)(tyTuple__kN8up2W6YKc5YA9avn5mV5w info__Lx1f8FCvObDpEKVCv0LvrQ);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s__qL2AkrAohOvo9bZZC15G6TA, NI addlen__uGPPC8Yor9a9avOoki7IG3AQ);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_198)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg, NI x__ei4a8HqkfxKmzlWy521zOg);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_176)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg_2, NI64 x__ei4a8HqkfxKmzlWy521zOg_2);
N_LIB_PRIVATE N_NIMCALL(void, internalErrorImpl__msgs_1507)(tyObject_ConfigRefcolonObjectType___2BjaRtGfBjUbX51p9a4g9a9cg* conf__j8Ms5zXQsUrdf80ByvZXLg, tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg info__n2ojTJDGPl67cpDvO1R9aFA, NimStringV2 errMsg__MqwY89aOVpFRguzrTi9bMoTA, tyTuple__kN8up2W6YKc5YA9avn5mV5w info2__WjGXKmxpztPih3PprVYTlQ);
N_LIB_PRIVATE N_NIMCALL(void, annotateType__semmacrosanity_70)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__JqvDhZLUORA89aOZiXt4S9bg, tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* t__nVh485SjA8eNVsxqKSlwNA, tyObject_ConfigRefcolonObjectType___2BjaRtGfBjUbX51p9a4g9a9cg* conf__pssxyazOm339c20lo1r05Vw);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___ast_4060)(tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA** dest__grSiItv7LycMhpeWUvBn0A_2);
static N_INLINE(NI, len__ast_5071)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* n__XTPkz1jrUDzaDAHPseflHQ_2);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q*, newNodeI__ast_3949)(tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ kind__35zUnl0k1aZrN8gnigVMNw, tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg info__hzqkjlKeMhH0EcinHaxNSw);
N_LIB_PRIVATE N_NIMCALL(void, add__ast_6233)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* father__MB9boMZEwZJkcDTaSQcQGbw, tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* son__au1P589a2NoDlzqIxdjigNQ);
N_LIB_PRIVATE N_NIMCALL(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q*, newIntNode__ast_4791)(tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ kind__W6hfr8to3DQjaHYQpDXstw, NI64 intVal__BLWM72ZjOoXgaVHSwpPVjQ);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_3469)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* dest__xUGZnk6LgW9ckUtke9chKW3g_3, tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* src__vkZbm6WIEuiiRIu4TGi3lg_3);
static N_INLINE(NI, safeLen__ast_3318)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__N6lgafW6ph3i7ySOoXUzXQ);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___ast_3457)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q** dest__xUGZnk6LgW9ckUtke9chKW3g_2, tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* src__vkZbm6WIEuiiRIu4TGi3lg_2);
N_LIB_PRIVATE N_NIMCALL(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA*, elemType__types_264)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* t__skRwjEiCze4lupAR71qAbA);
static NIM_CONST tySet_tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ TM__R7okQSC9beJ64olJCnqhGsw_2 = {
0x10, 0xa9, 0x10, 0x00, 0x00, 0x60, 0x80, 0x00,
0x00}
;
static NIM_CONST tySet_tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ TM__R7okQSC9beJ64olJCnqhGsw_3 = {
0x10, 0xa9, 0xe0, 0x00, 0x00, 0xe0, 0x80, 0x00,
0x00}
;
static NIM_CONST tySet_tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ TM__R7okQSC9beJ64olJCnqhGsw_4 = {
0x10, 0x09, 0xe0, 0x00, 0x00, 0xe0, 0x80, 0x00,
0x00}
;
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__R7okQSC9beJ64olJCnqhGsw_5 = { 23 | NIM_STRLIT_FLAG, "invalid field at index " };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_6 = {23, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_5};
static const struct {
  NI cap; NIM_CHAR data[44+1];
} TM__R7okQSC9beJ64olJCnqhGsw_8 = { 44 | NIM_STRLIT_FLAG, "/home/wind/nimv2/compiler/semmacrosanity.nim" };
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__R7okQSC9beJ64olJCnqhGsw_9 = { 1 | NIM_STRLIT_FLAG, "(" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_10 = {1, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_9};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__R7okQSC9beJ64olJCnqhGsw_11 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_12 = {2, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_11};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__R7okQSC9beJ64olJCnqhGsw_13 = { 1 | NIM_STRLIT_FLAG, ")" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_14 = {1, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_13};
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_16 = {23, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_5};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__R7okQSC9beJ64olJCnqhGsw_18 = { 34 | NIM_STRLIT_FLAG, "Incorrectly generated tuple constr" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_19 = {34, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_18};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__R7okQSC9beJ64olJCnqhGsw_21 = { 25 | NIM_STRLIT_FLAG, "() must have a tuple type" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_22 = {25, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_21};
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__R7okQSC9beJ64olJCnqhGsw_24 = { 36 | NIM_STRLIT_FLAG, "[] must have some form of array type" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_25 = {36, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_24};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__R7okQSC9beJ64olJCnqhGsw_27 = { 25 | NIM_STRLIT_FLAG, "{} must have the set type" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_28 = {25, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_27};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__R7okQSC9beJ64olJCnqhGsw_30 = { 39 | NIM_STRLIT_FLAG, "float literal must have some float type" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_31 = {39, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_30};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__R7okQSC9beJ64olJCnqhGsw_33 = { 39 | NIM_STRLIT_FLAG, "integer literal must have some int type" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_34 = {39, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_33};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__R7okQSC9beJ64olJCnqhGsw_36 = { 42 | NIM_STRLIT_FLAG, "string literal must be of some string type" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_37 = {42, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_36};
static const struct {
  NI cap; NIM_CHAR data[40+1];
} TM__R7okQSC9beJ64olJCnqhGsw_39 = { 40 | NIM_STRLIT_FLAG, "nil literal must be of some pointer type" };
static const NimStringV2 TM__R7okQSC9beJ64olJCnqhGsw_40 = {40, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_39};
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_7 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)58),
((NI)8)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_15 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)60),
((NI)22)}
;
extern NIM_CONST tyObject_TLineInfo__7ZAGqjaN6WqWPlHP9cRagRg unknownLineInfo__lineinfos_350;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_17 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)66),
((NI)23)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_20 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)87),
((NI)21)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_23 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)92),
((NI)17)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_26 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)98),
((NI)17)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_29 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)104),
((NI)17)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_32 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)109),
((NI)17)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_35 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)114),
((NI)17)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_38 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)119),
((NI)17)}
;
static NIM_CONST tyTuple__kN8up2W6YKc5YA9avn5mV5w TM__R7okQSC9beJ64olJCnqhGsw_41 = {{44, (NimStrPayload*)&TM__R7okQSC9beJ64olJCnqhGsw_8},
((NI)124),
((NI)17)}
;
extern NIM_BOOL nimInErrorMode__system_3980;
static N_INLINE(NI, len__ast_3325)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__XTPkz1jrUDzaDAHPseflHQ) {
	NI result;
	NI T1_;
	result = (NI)0;
	T1_ = (*n__XTPkz1jrUDzaDAHPseflHQ)._kind_6.sons.len;
	result = T1_;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3980);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*, ithField__semmacrosanity_5)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__yXlfnFjgNaWS51AFbh8yGQ, NI* field__tsAB9bChXl34vu09cEjrc2vQ_2) {
	tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* result;
NIM_BOOL oldNimErrFin24_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	result = ((tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*) NIM_NIL);
	switch ((*n__yXlfnFjgNaWS51AFbh8yGQ).kind) {
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)138):
	{
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = len__ast_3325(n__yXlfnFjgNaWS51AFbh8yGQ);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			i_2 = ((NI)0);
			{
				while (1) {
					tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* T5_;
					if (!(i_2 < colontmp_)) goto LA4					;
					i = i_2;
					T5_ = NIM_NIL;
					T5_ = ithField__semmacrosanity_5((*n__yXlfnFjgNaWS51AFbh8yGQ)._kind_6.sons.p->data[i], field__tsAB9bChXl34vu09cEjrc2vQ_2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					eqsink___ast_4066(&result, T5_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					{
						if (!!((result == ((tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*) NIM_NIL)))) goto LA8_;
						goto BeforeRet_;
					}
					LA8_: ;
					i_2 += ((NI)1);
				} LA4: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)139):
	{
		tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* T15_;
		{
			if (!!(((*(*n__yXlfnFjgNaWS51AFbh8yGQ)._kind_6.sons.p->data[((NI)0)]).kind == ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)3)))) goto LA13_;
			goto BeforeRet_;
		}
		LA13_: ;
		T15_ = NIM_NIL;
		T15_ = ithField__semmacrosanity_5((*n__yXlfnFjgNaWS51AFbh8yGQ)._kind_6.sons.p->data[((NI)0)], field__tsAB9bChXl34vu09cEjrc2vQ_2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqsink___ast_4066(&result, T15_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			if (!!((result == ((tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*) NIM_NIL)))) goto LA18_;
			goto BeforeRet_;
		}
		LA18_: ;
		{
			NI i_3;
			NI colontmp__2;
			NI i_4;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = len__ast_3325(n__yXlfnFjgNaWS51AFbh8yGQ);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			i_4 = ((NI)1);
			{
				while (1) {
					if (!(i_4 < colontmp__2)) goto LA22					;
					i_3 = i_4;
					switch ((*(*n__yXlfnFjgNaWS51AFbh8yGQ)._kind_6.sons.p->data[i_3]).kind) {
					case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)85):
					case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)88):
					{
						tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* colontmpD_;
						tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* T25_;
						colontmpD_ = NIM_NIL;
						colontmpD_ = lastSon__ast_6268((*n__yXlfnFjgNaWS51AFbh8yGQ)._kind_6.sons.p->data[i_3]);
						if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
						T25_ = NIM_NIL;
						T25_ = ithField__semmacrosanity_5(colontmpD_, field__tsAB9bChXl34vu09cEjrc2vQ_2);
						if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
						eqsink___ast_4066(&result, T25_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA24_;
						{
							if (!!((result == ((tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*) NIM_NIL)))) goto LA28_;
							eqdestroy___ast_3454(&colontmpD_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							goto BeforeRet_;
						}
						LA28_: ;
						{
							LA24_:;
						}
						{
							oldNimErrFin24_ = *nimErr_; *nimErr_ = NIM_FALSE;
							eqdestroy___ast_3454(&colontmpD_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							*nimErr_ = oldNimErrFin24_;
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					break;
					default:
					{
					}
					break;
					}
					i_4 += ((NI)1);
				} LA22: ;
			}
		}
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)3):
	{
		{
			if (!((*field__tsAB9bChXl34vu09cEjrc2vQ_2) == ((NI)0))) goto LA36_;
			eqcopy___ast_4063(&result, (*n__yXlfnFjgNaWS51AFbh8yGQ)._kind_4.sym);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA34_;
		LA36_: ;
		{
			(*field__tsAB9bChXl34vu09cEjrc2vQ_2) -= ((NI)1);
		}
		LA34_: ;
	}
	break;
	default:
	{
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*, ithField__semmacrosanity_54)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* t__oDmrDxr0nf8ja80Q9aQnFsQ, NI* field__tsAB9bChXl34vu09cEjrc2vQ) {
	tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* result;
	tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* base;
NIM_BOOL oldNimErrFin4_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	base = NIM_NIL;
	eqcopy___ast_3546(&base, (*t__oDmrDxr0nf8ja80Q9aQnFsQ).sons.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		while (1) {
			tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* b;
			tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* T5_;
			if (!!((base == ((tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA*) NIM_NIL)))) goto LA3			;
			b = NIM_NIL;
			b = skipTypes__ast_4803(base, TM__R7okQSC9beJ64olJCnqhGsw_4);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			T5_ = NIM_NIL;
			T5_ = ithField__semmacrosanity_5((*b).n, field__tsAB9bChXl34vu09cEjrc2vQ);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			eqsink___ast_4066(&result, T5_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			{
				if (!!((result == ((tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA*) NIM_NIL)))) goto LA8_;
				eqdestroy___ast_3543(&b);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				eqdestroy___ast_3543(&base);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				goto BeforeRet_;
			}
			LA8_: ;
			eqcopy___ast_3546(&base, (*b).sons.p->data[((NI)0)]);
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			{
				LA4_:;
			}
			{
				oldNimErrFin4_ = *nimErr_; *nimErr_ = NIM_FALSE;
				eqdestroy___ast_3543(&b);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				*nimErr_ = oldNimErrFin4_;
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		} LA3: ;
	}
	result = ithField__semmacrosanity_5((*t__oDmrDxr0nf8ja80Q9aQnFsQ).n, field__tsAB9bChXl34vu09cEjrc2vQ);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___ast_3543(&base);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));
}
static N_INLINE(void, copyMem__system_1719)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g) {
	{
		if (!(((NI)0) < src__369aqaoei6FUsRf9cDAsKQ2g.len)) goto LA3_;
		copyMem__system_1719(((void*) ((&(*(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).p).data[(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len]))), ((void*) ((&(*src__369aqaoei6FUsRf9cDAsKQ2g.p).data[((NI)0)]))), ((NI) ((NI)(src__369aqaoei6FUsRf9cDAsKQ2g.len + ((NI)1)))));
		(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len += src__369aqaoei6FUsRf9cDAsKQ2g.len;
	}
	LA3_: ;
}
static N_INLINE(void, addInt__stdZprivateZdigitsutils_198)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg, NI x__ei4a8HqkfxKmzlWy521zOg) {
	addInt__stdZprivateZdigitsutils_176(result__eysCSqL57sYgaohCkVYRVg, ((NI64) (x__ei4a8HqkfxKmzlWy521zOg)));
}
static N_INLINE(NimStringV2, toFileLineCol__msgs_664)(tyTuple__kN8up2W6YKc5YA9avn5mV5w info__Lx1f8FCvObDpEKVCv0LvrQ) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	prepareAdd((&result), info__Lx1f8FCvObDpEKVCv0LvrQ.Field0.len + 0);
appendString((&result), info__Lx1f8FCvObDpEKVCv0LvrQ.Field0);
	{
		if (!(((NI)0) < info__Lx1f8FCvObDpEKVCv0LvrQ.Field1)) goto LA3_;
		prepareAdd((&result), 1);
appendString((&result), TM__R7okQSC9beJ64olJCnqhGsw_10);
		addInt__stdZprivateZdigitsutils_198((&result), info__Lx1f8FCvObDpEKVCv0LvrQ.Field1);
		{
			if (!(((NI)0) < (NI)(info__Lx1f8FCvObDpEKVCv0LvrQ.Field2 + ((NI)1)))) goto LA7_;
			prepareAdd((&result), 2);
appendString((&result), TM__R7okQSC9beJ64olJCnqhGsw_12);
			addInt__stdZprivateZdigitsutils_198((&result), (NI)(info__Lx1f8FCvObDpEKVCv0LvrQ.Field2 + ((NI)1)));
		}
		LA7_: ;
		prepareAdd((&result), 1);
appendString((&result), TM__R7okQSC9beJ64olJCnqhGsw_14);
	}
	LA3_: ;
	return result;
}
static N_INLINE(NI, len__ast_5071)(tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* n__XTPkz1jrUDzaDAHPseflHQ_2) {
	NI result;
	NI T1_;
	result = (NI)0;
	T1_ = (*n__XTPkz1jrUDzaDAHPseflHQ_2).sons.len;
	result = T1_;
	return result;
}
static N_INLINE(NI, safeLen__ast_3318)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__N6lgafW6ph3i7ySOoXUzXQ) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!((*n__N6lgafW6ph3i7ySOoXUzXQ).kind >= ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)0) && (*n__N6lgafW6ph3i7ySOoXUzXQ).kind <= ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)23))) goto LA3_;
		result = ((NI)0);
	}
	goto LA1_;
	LA3_: ;
	{
		result = len__ast_3325(n__N6lgafW6ph3i7ySOoXUzXQ);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, annotateType__semmacrosanity_70)(tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* n__JqvDhZLUORA89aOZiXt4S9bg, tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* t__nVh485SjA8eNVsxqKSlwNA, tyObject_ConfigRefcolonObjectType___2BjaRtGfBjUbX51p9a4g9a9cg* conf__pssxyazOm339c20lo1r05Vw) {
	tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* x;
NIM_BOOL oldNimErrFin7_;
NIM_BOOL oldNimErrFin3_;
NIM_BOOL oldNimErrFin63_;
NIM_BOOL oldNimErrFin58_;
NIM_BOOL oldNimErrFin86_;
NIM_BOOL oldNimErrFin82_;
NIM_BOOL oldNimErrFin102_;
NIM_BOOL oldNimErrFin98_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	x = NIM_NIL;
	x = skipTypes__ast_4803(t__nVh485SjA8eNVsxqKSlwNA, TM__R7okQSC9beJ64olJCnqhGsw_2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	switch ((*n__JqvDhZLUORA89aOZiXt4S9bg).kind) {
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)38):
	{
		tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* x_2;
		x_2 = NIM_NIL;
		x_2 = skipTypes__ast_4803(t__nVh485SjA8eNVsxqKSlwNA, TM__R7okQSC9beJ64olJCnqhGsw_3);
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
		if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = len__ast_3325(n__JqvDhZLUORA89aOZiXt4S9bg);
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
			i_2 = ((NI)1);
			{
				while (1) {
					tyObject_TSym__9cob5UPXvLCxy8mslvxEYzA* field;
					NI j;
					if (!(i_2 < colontmp_)) goto LA6					;
					field = NIM_NIL;
					i = i_2;
					j = (NI)(i - ((NI)1));
					field = ithField__semmacrosanity_54(x_2, (&j));
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					{
						NimStringV2 colontmpD_;
						NimStringV2 colontmpD__2;
						NimStringV2 T13_;
						if (!(field == 0)) goto LA10_;
						colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
						colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
						T13_.len = 0; T13_.p = NIM_NIL;
						colontmpD_ = dollar___systemZdollars_3(i);
						if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
						T13_ = rawNewString(colontmpD_.len + 23);
appendString((&T13_), TM__R7okQSC9beJ64olJCnqhGsw_6);
appendString((&T13_), colontmpD_);
						colontmpD__2 = T13_;
						liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), colontmpD__2, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_7, NIM_FALSE);
						if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
						{
							LA12_:;
						}
						{
							eqdestroy___stdZassertions_13((&colontmpD__2));
							eqdestroy___stdZassertions_13((&colontmpD_));
						}
						if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					}
					goto LA8_;
					LA10_: ;
					{
						{
							NimStringV2 argX60gensym16_;
							if (!!(((*(*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[i]).kind == ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)34)))) goto LA19_;
							argX60gensym16_.len = 0; argX60gensym16_.p = NIM_NIL;
							argX60gensym16_ = toFileLineCol__msgs_664(TM__R7okQSC9beJ64olJCnqhGsw_15);
							if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
							internalErrorImpl__msgs_1507(conf__pssxyazOm339c20lo1r05Vw, unknownLineInfo__lineinfos_350, argX60gensym16_, TM__R7okQSC9beJ64olJCnqhGsw_15);
							if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
							{
								LA21_:;
							}
							{
								eqdestroy___stdZassertions_13((&argX60gensym16_));
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
						}
						LA19_: ;
						annotateType__semmacrosanity_70((*(*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[i])._kind_6.sons.p->data[((NI)1)], (*field).typ, conf__pssxyazOm339c20lo1r05Vw);
						if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					}
					LA8_: ;
					i_2 += ((NI)1);
					{
						LA7_:;
					}
					{
						oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
						eqdestroy___ast_4060(&field);
						if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
						*nimErr_ = oldNimErrFin7_;
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
				} LA6: ;
			}
		}
		{
			LA3_:;
		}
		{
			oldNimErrFin3_ = *nimErr_; *nimErr_ = NIM_FALSE;
			eqdestroy___ast_3543(&x_2);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin3_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)37):
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)160):
	{
		{
			if (!((*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)18))) goto LA31_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				NI i_3;
				NI colontmp__2;
				NI i_4;
				i_3 = (NI)0;
				colontmp__2 = (NI)0;
				colontmp__2 = len__ast_3325(n__JqvDhZLUORA89aOZiXt4S9bg);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				i_4 = ((NI)0);
				{
					while (1) {
						if (!(i_4 < colontmp__2)) goto LA35						;
						i_3 = i_4;
						{
							NI T38_;
							NimStringV2 colontmpD__3;
							NimStringV2 colontmpD__4;
							NimStringV2 T42_;
							T38_ = (NI)0;
							T38_ = len__ast_5071(x);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
							if (!(T38_ <= i_3)) goto LA39_;
							colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
							colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
							T42_.len = 0; T42_.p = NIM_NIL;
							colontmpD__3 = dollar___systemZdollars_3(i_3);
							if (NIM_UNLIKELY(*nimErr_)) goto LA41_;
							T42_ = rawNewString(colontmpD__3.len + 23);
appendString((&T42_), TM__R7okQSC9beJ64olJCnqhGsw_16);
appendString((&T42_), colontmpD__3);
							colontmpD__4 = T42_;
							liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), colontmpD__4, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_17, NIM_FALSE);
							if (NIM_UNLIKELY(*nimErr_)) goto LA41_;
							{
								LA41_:;
							}
							{
								eqdestroy___stdZassertions_13((&colontmpD__4));
								eqdestroy___stdZassertions_13((&colontmpD__3));
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
						}
						goto LA36_;
						LA39_: ;
						{
							annotateType__semmacrosanity_70((*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[i_3], (*x).sons.p->data[i_3], conf__pssxyazOm339c20lo1r05Vw);
							if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
						}
						LA36_: ;
						i_4 += ((NI)1);
					} LA35: ;
				}
			}
		}
		goto LA29_;
		LA31_: ;
		{
			NIM_BOOL T47_;
			T47_ = (NIM_BOOL)0;
			T47_ = ((*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)25));
			if (!(T47_)) goto LA48_;
			T47_ = ((*x).callConv == ((tyEnum_TCallingConvention__XL1p2EKvOAlAHpc68ecZPw)9));
			LA48_: ;
			if (!T47_) goto LA49_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA29_;
		LA49_: ;
		{
			if (!((*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)27))) goto LA52_;
			{
				tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* bracketExpr;
				NI left;
				NI right;
				if (!((*n__JqvDhZLUORA89aOZiXt4S9bg).kind == ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)160))) goto LA56_;
				bracketExpr = NIM_NIL;
				bracketExpr = newNodeI__ast_3949(((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)41), (*n__JqvDhZLUORA89aOZiXt4S9bg).info);
				if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
				left = ((NI) ((*(*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[((NI)1)])._kind_1.intVal));
				right = ((NI) ((*(*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[((NI)2)])._kind_1.intVal));
				(*bracketExpr).flags = (*n__JqvDhZLUORA89aOZiXt4S9bg).flags;
				switch ((*(*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[((NI)0)]).kind) {
				case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)20) ... ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)22):
				{
					{
						NI i_5;
						NI res;
						i_5 = (NI)0;
						res = left;
						{
							while (1) {
								tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* colontmpD__5;
								NI T64_;
								if (!(res <= right)) goto LA62								;
								colontmpD__5 = NIM_NIL;
								i_5 = res;
								colontmpD__5 = newIntNode__ast_4791(((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)5), ((NI64) (((NU8)((*(*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[((NI)0)])._kind_3.strVal.p->data[i_5])))));
								if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
								add__ast_6233(bracketExpr, colontmpD__5);
								if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
								T64_ = (NI)0;
								T64_ = len__ast_3325(bracketExpr);
								if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
								annotateType__semmacrosanity_70((*bracketExpr)._kind_6.sons.p->data[(NI)(T64_ - ((NI)1))], (*t__nVh485SjA8eNVsxqKSlwNA).sons.p->data[((NI)0)], conf__pssxyazOm339c20lo1r05Vw);
								if (NIM_UNLIKELY(*nimErr_)) goto LA63_;
								res += ((NI)1);
								{
									LA63_:;
								}
								{
									oldNimErrFin63_ = *nimErr_; *nimErr_ = NIM_FALSE;
									eqdestroy___ast_3454(&colontmpD__5);
									if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
									*nimErr_ = oldNimErrFin63_;
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
							} LA62: ;
						}
					}
				}
				break;
				case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)41):
				{
					{
						NI i_6;
						NI res_2;
						i_6 = (NI)0;
						res_2 = left;
						{
							while (1) {
								NI T71_;
								if (!(res_2 <= right)) goto LA70								;
								i_6 = res_2;
								add__ast_6233(bracketExpr, (*(*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[((NI)0)])._kind_6.sons.p->data[i_6]);
								if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
								T71_ = (NI)0;
								T71_ = len__ast_3325(bracketExpr);
								if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
								annotateType__semmacrosanity_70((*bracketExpr)._kind_6.sons.p->data[(NI)(T71_ - ((NI)1))], (*t__nVh485SjA8eNVsxqKSlwNA).sons.p->data[((NI)0)], conf__pssxyazOm339c20lo1r05Vw);
								if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
								res_2 += ((NI)1);
							} LA70: ;
						}
					}
				}
				break;
				default:
				{
					liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_19, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_20, NIM_FALSE);
					if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
				}
				break;
				}
				eqcopy___ast_3469(n__JqvDhZLUORA89aOZiXt4S9bg, (&(*bracketExpr)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA58_;
				{
					LA58_:;
				}
				{
					oldNimErrFin58_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___ast_3454(&bracketExpr);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin58_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
			LA56_: ;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA29_;
		LA52_: ;
		{
			liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_22, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_23, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA29_: ;
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)41):
	{
		{
			if (!((*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)16) || (*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)24) || (*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)27))) goto LA79_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* m;
				m = NIM_NIL;
				{
					NI i_7;
					NI colontmp__3;
					NI i_8;
					i_7 = (NI)0;
					colontmp__3 = (NI)0;
					colontmp__3 = safeLen__ast_3318(n__JqvDhZLUORA89aOZiXt4S9bg);
					if (NIM_UNLIKELY(*nimErr_)) goto LA82_;
					i_8 = ((NI)0);
					{
						while (1) {
							tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* colontmpD__6;
							if (!(i_8 < colontmp__3)) goto LA85							;
							colontmpD__6 = NIM_NIL;
							i_7 = i_8;
							eqcopy___ast_3457(&m, (*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[i_7]);
							if (NIM_UNLIKELY(*nimErr_)) goto LA86_;
							colontmpD__6 = elemType__types_264(x);
							if (NIM_UNLIKELY(*nimErr_)) goto LA86_;
							annotateType__semmacrosanity_70(m, colontmpD__6, conf__pssxyazOm339c20lo1r05Vw);
							if (NIM_UNLIKELY(*nimErr_)) goto LA86_;
							i_8 += ((NI)1);
							{
								LA86_:;
							}
							{
								oldNimErrFin86_ = *nimErr_; *nimErr_ = NIM_FALSE;
								eqdestroy___ast_3543(&colontmpD__6);
								if (NIM_UNLIKELY(*nimErr_)) goto LA82_;
								*nimErr_ = oldNimErrFin86_;
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA82_;
						} LA85: ;
					}
				}
				{
					LA82_:;
				}
				{
					oldNimErrFin82_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___ast_3454(&m);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin82_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
		}
		goto LA77_;
		LA79_: ;
		{
			liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_25, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_26, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA77_: ;
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)39):
	{
		{
			if (!((*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)19))) goto LA95_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			{
				tyObject_TNode__1pEudI6ZemBfsBxMjg4u5Q* m_2;
				m_2 = NIM_NIL;
				{
					NI i_9;
					NI colontmp__4;
					NI i_10;
					i_9 = (NI)0;
					colontmp__4 = (NI)0;
					colontmp__4 = safeLen__ast_3318(n__JqvDhZLUORA89aOZiXt4S9bg);
					if (NIM_UNLIKELY(*nimErr_)) goto LA98_;
					i_10 = ((NI)0);
					{
						while (1) {
							tyObject_TType__qs8ld9cHTjcxh7xYsvWduXA* colontmpD__7;
							if (!(i_10 < colontmp__4)) goto LA101							;
							colontmpD__7 = NIM_NIL;
							i_9 = i_10;
							eqcopy___ast_3457(&m_2, (*n__JqvDhZLUORA89aOZiXt4S9bg)._kind_6.sons.p->data[i_9]);
							if (NIM_UNLIKELY(*nimErr_)) goto LA102_;
							colontmpD__7 = elemType__types_264(x);
							if (NIM_UNLIKELY(*nimErr_)) goto LA102_;
							annotateType__semmacrosanity_70(m_2, colontmpD__7, conf__pssxyazOm339c20lo1r05Vw);
							if (NIM_UNLIKELY(*nimErr_)) goto LA102_;
							i_10 += ((NI)1);
							{
								LA102_:;
							}
							{
								oldNimErrFin102_ = *nimErr_; *nimErr_ = NIM_FALSE;
								eqdestroy___ast_3543(&colontmpD__7);
								if (NIM_UNLIKELY(*nimErr_)) goto LA98_;
								*nimErr_ = oldNimErrFin102_;
							}
							if (NIM_UNLIKELY(*nimErr_)) goto LA98_;
						} LA101: ;
					}
				}
				{
					LA98_:;
				}
				{
					oldNimErrFin98_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___ast_3454(&m_2);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin98_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			}
		}
		goto LA93_;
		LA95_: ;
		{
			liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_28, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_29, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA93_: ;
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)16) ... ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)19):
	{
		{
			if (!((*x).kind >= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)36) && (*x).kind <= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)39))) goto LA111_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA109_;
		LA111_: ;
		{
			liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_31, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_32, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA109_: ;
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)5) ... ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)15):
	{
		{
			if (!((*x).kind >= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)31) && (*x).kind <= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)44) || (*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)1) || (*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)2) || (*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)14))) goto LA117_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA115_;
		LA117_: ;
		{
			liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_34, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_35, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA115_: ;
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)20) ... ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)22):
	{
		{
			if (!((*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)28) || (*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)29))) goto LA123_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA121_;
		LA123_: ;
		{
			liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_37, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_38, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA121_: ;
	}
	break;
	case ((tyEnum_TNodeKind__ySM4MdHjvuRpNcphR1xnyQ)23):
	{
		{
			if (!((*x).kind >= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)21) && (*x).kind <= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)22) || (*x).kind >= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)24) && (*x).kind <= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)26) || (*x).kind >= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)28) && (*x).kind <= ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)29) || (*x).kind == ((tyEnum_TTypeKind__cu4lI59aFp7m9cDkg2Nfr7ZQ)50))) goto LA129_;
			eqcopy___ast_3546(&(*n__JqvDhZLUORA89aOZiXt4S9bg).typ, t__nVh485SjA8eNVsxqKSlwNA);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		goto LA127_;
		LA129_: ;
		{
			liMessage__msgs_1169(conf__pssxyazOm339c20lo1r05Vw, (*n__JqvDhZLUORA89aOZiXt4S9bg).info, ((tyEnum_TMsgKind__9b1zBSEXe8I2R9aa2h3NYf9cA)17), TM__R7okQSC9beJ64olJCnqhGsw_40, ((tyEnum_TErrorHandling__NXH4RLc649bsDWofENjZIqw)2), TM__R7okQSC9beJ64olJCnqhGsw_41, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA127_: ;
	}
	break;
	default:
	{
	}
	break;
	}
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___ast_3543(&x);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
