/* Generated by Nim Compiler v1.9.1 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct TNimTypeV2 {
void* destructor;
NI size;
NI16 align;
NI16 depth;
NU32* display;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg {
  RootObj Sup;
NI bufpos;
NimStringV2 buf;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstreams_616)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ** dest__UR7eUPUKn59cgUFb9csNd7DQ, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* src__P4co8QvsVH1kTz4sfKnhTw, NIM_BOOL cyclic__kknf9cfhePxJk7ZDUgotYiA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___stdZassertions_19)(NimStringV2* dest__VTJh4gw5Rje9bocjsx81Ekg, NimStringV2 src__GJAw6lOoetbnH4F11f7wrg);
N_NIMCALL(NimStringV2, mnewString)(NI len__AJLhA35Y49afqnWtWvCnn4w);
N_LIB_PRIVATE N_NIMCALL(void, fillBuffer__pureZlexbase_17)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__SyiqRnH0UhmSG9cCf9bbVYmA);
static N_INLINE(void, moveMem__system_1723)(void* dest__q64ikw2oOp0CzaioKiMWsQ, void* source__C5aLKOrO9blo7qfbDSZOuTw, NI size__evxXl5Dwm42BhqRuLY7ZRw);
N_LIB_PRIVATE N_NIMCALL(NI, readDataStr__pureZstreams_85)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__YTCin9cHdZcIaH9aBFD7HKtQ, NimStringV2* buffer__6gkf4wMbm6NSISLb7tYEgQ, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA slice__TFKaxsXiphqppzIlAf2xNw);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___stdZstrbasics_49)(NI a__KjwZroJB1iMTsXN9b0MEieA, NI b__m9c8KJepQ6mBYDEvipBikTw);
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s__loo5Z73wZsb5OCeQPiUDYg);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2301)(NimStringV2* s__9azXNueo9acOrj8WVyZabYtg);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s__19atMbr42TbRkrQSPFxaPZg, NI newLen__zdmruIpEqwmFKxid9btfbJw);
N_LIB_PRIVATE N_NIMCALL(void, skipUtf8Bom__pureZlexbase_119)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__txiD8EQIeNgClZiKNsDZNA);
N_LIB_PRIVATE N_NIMCALL(NI, fillBaseLexer__pureZlexbase_73)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__BQxEos4qLx7OR8R0OelLiQ, NI pos__z0h0lmOUpFv23CDAlYgm5g);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_58)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s__qYFvro9cLG9by9cSabBsxwxpA);
extern NIM_BOOL nimInErrorMode__system_3978;
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));
}
static N_INLINE(void, moveMem__system_1723)(void* dest__q64ikw2oOp0CzaioKiMWsQ, void* source__C5aLKOrO9blo7qfbDSZOuTw, NI size__evxXl5Dwm42BhqRuLY7ZRw) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memmove(dest__q64ikw2oOp0CzaioKiMWsQ, source__C5aLKOrO9blo7qfbDSZOuTw, ((size_t) (size__evxXl5Dwm42BhqRuLY7ZRw)));
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a__tZiCJHYy5dYyAh9cxwrrVhQ, v__iM7JOvZxArJIvbhGyRZG6Q, ((size_t) (size__ntsFNLS0mpvnjQFrZT7DCw)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3978);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p__BuPKoq7dppy2upaj3KUaxw, ((int)0), size__ttWVm79bajRU3tarcA7MkLw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___stdZstrbasics_49)(NI a__KjwZroJB1iMTsXN9b0MEieA, NI b__m9c8KJepQ6mBYDEvipBikTw) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a__KjwZroJB1iMTsXN9b0MEieA;
	result.b = b__m9c8KJepQ6mBYDEvipBikTw;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s__loo5Z73wZsb5OCeQPiUDYg) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s__loo5Z73wZsb5OCeQPiUDYg).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s__loo5Z73wZsb5OCeQPiUDYg).p).cap & ((NI)1073741824)) == ((NI)1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_2301(s__loo5Z73wZsb5OCeQPiUDYg);
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, fillBuffer__pureZlexbase_17)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__SyiqRnH0UhmSG9cCf9bbVYmA) {
	NI charsRead;
	NI toCopy;
	NI s;
	NI oldBufLen;
	tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* T6_;
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T7_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	charsRead = (NI)0;
	toCopy = (NI)0;
	s = (NI)0;
	oldBufLen = (NI)0;
	toCopy = (NI)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.len - (NI)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).sentinel + ((NI)1)));
	{
		void* T5_;
		if (!(((NI)0) < toCopy)) goto LA3_;
		T5_ = (void*)0;
		T5_ = ((void*) ((&(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.p->data[((NI)0)])));
		moveMem__system_1723(T5_, ((void*) ((&(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.p->data[(NI)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).sentinel + ((NI)1))]))), ((NI) (toCopy)));
	}
	LA3_: ;
	T6_ = NIM_NIL;
	T6_ = (*L__SyiqRnH0UhmSG9cCf9bbVYmA).input;
	T7_ = dotdot___stdZstrbasics_49(toCopy, (NI)((NI)((NI)(toCopy + (*L__SyiqRnH0UhmSG9cCf9bbVYmA).sentinel) + ((NI)1)) - ((NI)1)));
	charsRead = readDataStr__pureZstreams_85(T6_, (&(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf), T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	s = (NI)(toCopy + charsRead);
	{
		if (!(charsRead < (NI)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).sentinel + ((NI)1)))) goto LA10_;
		nimPrepareStrMutationV2((&(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf));
		(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.p->data[s] = 0;
		(*L__SyiqRnH0UhmSG9cCf9bbVYmA).sentinel = s;
	}
	goto LA8_;
	LA10_: ;
	{
		s -= ((NI)1);
		{
			while (1) {
				{
					while (1) {
						NIM_BOOL T17_;
						T17_ = (NIM_BOOL)0;
						T17_ = (((NI)0) <= s);
						if (!(T17_)) goto LA18_;
						T17_ = !((((*L__SyiqRnH0UhmSG9cCf9bbVYmA).refillChars[(NU)((((NU8)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.p->data[s]))))>>3] &(1U<<((NU)((((NU8)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.p->data[s]))))&7U)))!=0));
						LA18_: ;
						if (!T17_) goto LA16						;
						s -= ((NI)1);
					} LA16: ;
				}
				{
					if (!(((NI)0) <= s)) goto LA21_;
					(*L__SyiqRnH0UhmSG9cCf9bbVYmA).sentinel = s;
					goto LA13;
				}
				goto LA19_;
				LA21_: ;
				{
					tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* T24_;
					tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T25_;
					oldBufLen = (*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.len;
					setLengthStrV2((&(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf), ((NI) ((NI)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.len * ((NI)2)))));
					T24_ = NIM_NIL;
					T24_ = (*L__SyiqRnH0UhmSG9cCf9bbVYmA).input;
					T25_ = dotdot___stdZstrbasics_49(oldBufLen, (NI)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.len - ((NI)1)));
					charsRead = readDataStr__pureZstreams_85(T24_, (&(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf), T25_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					{
						if (!(charsRead < oldBufLen)) goto LA28_;
						nimPrepareStrMutationV2((&(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf));
						(*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.p->data[(NI)(oldBufLen + charsRead)] = 0;
						(*L__SyiqRnH0UhmSG9cCf9bbVYmA).sentinel = (NI)(oldBufLen + charsRead);
						goto LA13;
					}
					LA28_: ;
					s = (NI)((*L__SyiqRnH0UhmSG9cCf9bbVYmA).buf.len - ((NI)1));
				}
				LA19_: ;
			}
		} LA13: ;
	}
	LA8_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, skipUtf8Bom__pureZlexbase_119)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__txiD8EQIeNgClZiKNsDZNA) {
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = ((NU8)((*L__txiD8EQIeNgClZiKNsDZNA).buf.p->data[((NI)0)]) == (NU8)(239));
		if (!(T4_)) goto LA5_;
		T4_ = ((NU8)((*L__txiD8EQIeNgClZiKNsDZNA).buf.p->data[((NI)1)]) == (NU8)(187));
		LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA6_;
		T3_ = ((NU8)((*L__txiD8EQIeNgClZiKNsDZNA).buf.p->data[((NI)2)]) == (NU8)(191));
		LA6_: ;
		if (!T3_) goto LA7_;
		(*L__txiD8EQIeNgClZiKNsDZNA).bufpos += ((NI)3);
		(*L__txiD8EQIeNgClZiKNsDZNA).lineStart += ((NI)3);
	}
	LA7_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_131)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__fvsBYw5pqqLNdeqWvDZXww, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input__ByZEADTLX4ih3OaPl9b9b6uA, NI bufLen__RDXsSh6AHCB04KbfYyjD4g, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars__7ExtrMVYOw81ndXrjR9cIyA) {
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqcopy___pureZstreams_616(&(*L__fvsBYw5pqqLNdeqWvDZXww).input, input__ByZEADTLX4ih3OaPl9b9b6uA, NIM_TRUE);
	(*L__fvsBYw5pqqLNdeqWvDZXww).bufpos = ((NI)0);
	(*L__fvsBYw5pqqLNdeqWvDZXww).offsetBase = ((NI)0);
	nimCopyMem((void*)(*L__fvsBYw5pqqLNdeqWvDZXww).refillChars, (NIM_CONST void*)refillChars__7ExtrMVYOw81ndXrjR9cIyA, 32);
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = mnewString(((NI) (bufLen__RDXsSh6AHCB04KbfYyjD4g)));
	eqsink___stdZassertions_19((&(*L__fvsBYw5pqqLNdeqWvDZXww).buf), T1_);
	(*L__fvsBYw5pqqLNdeqWvDZXww).sentinel = (NI)(bufLen__RDXsSh6AHCB04KbfYyjD4g - ((NI)1));
	(*L__fvsBYw5pqqLNdeqWvDZXww).lineStart = ((NI)0);
	(*L__fvsBYw5pqqLNdeqWvDZXww).lineNumber = ((NI)1);
	fillBuffer__pureZlexbase_17(L__fvsBYw5pqqLNdeqWvDZXww);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	skipUtf8Bom__pureZlexbase_119(L__fvsBYw5pqqLNdeqWvDZXww);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, fillBaseLexer__pureZlexbase_73)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__BQxEos4qLx7OR8R0OelLiQ, NI pos__z0h0lmOUpFv23CDAlYgm5g) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!(pos__z0h0lmOUpFv23CDAlYgm5g < (*L__BQxEos4qLx7OR8R0OelLiQ).sentinel)) goto LA3_;
		result = (NI)(pos__z0h0lmOUpFv23CDAlYgm5g + ((NI)1));
	}
	goto LA1_;
	LA3_: ;
	{
		fillBuffer__pureZlexbase_17(L__BQxEos4qLx7OR8R0OelLiQ);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*L__BQxEos4qLx7OR8R0OelLiQ).offsetBase += pos__z0h0lmOUpFv23CDAlYgm5g;
		(*L__BQxEos4qLx7OR8R0OelLiQ).bufpos = ((NI)0);
		result = ((NI)0);
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_84)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__GEOyasC0rSwnk4L55k8qjg, NI pos__ISppJfcjABM1rDUsMXSknQ) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	(*L__GEOyasC0rSwnk4L55k8qjg).lineNumber += ((NI)1);
	result = fillBaseLexer__pureZlexbase_73(L__GEOyasC0rSwnk4L55k8qjg, pos__ISppJfcjABM1rDUsMXSknQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!((NU8)((*L__GEOyasC0rSwnk4L55k8qjg).buf.p->data[result]) == (NU8)(10))) goto LA3_;
		result = fillBaseLexer__pureZlexbase_73(L__GEOyasC0rSwnk4L55k8qjg, result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	(*L__GEOyasC0rSwnk4L55k8qjg).lineStart = result;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_96)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__hDaDh3UY9aTMmQcO7YhAJ7w, NI pos__O0eYJKPQGmJS79bjg1OAF4A) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	(*L__hDaDh3UY9aTMmQcO7YhAJ7w).lineNumber += ((NI)1);
	result = fillBaseLexer__pureZlexbase_73(L__hDaDh3UY9aTMmQcO7YhAJ7w, pos__O0eYJKPQGmJS79bjg1OAF4A);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*L__hDaDh3UY9aTMmQcO7YhAJ7w).lineStart = result;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_146)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__Pg9cEAr79aDPGqavxRwbqRTw, NI pos__4TZ8TJPsPnj9bmMlvIQuGPw) {
	NI result;
	result = (NI)0;
	result = ((NI)(pos__4TZ8TJPsPnj9bmMlvIQuGPw - (*L__Pg9cEAr79aDPGqavxRwbqRTw).lineStart) > 0? ((NI)(pos__4TZ8TJPsPnj9bmMlvIQuGPw - (*L__Pg9cEAr79aDPGqavxRwbqRTw).lineStart)) : -((NI)(pos__4TZ8TJPsPnj9bmMlvIQuGPw - (*L__Pg9cEAr79aDPGqavxRwbqRTw).lineStart)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_15)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L__r8nBAOUarVkbaf4PwE4CQQ) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	close__pureZstreams_58((*L__r8nBAOUarVkbaf4PwE4CQQ).input);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
